'use strict';
window.createKnowledgeUI=({api,demo,toast})=>{
  const kinds={skill:'Skill',workflow:'工作流',prompt:'提示词',profile:'个人偏好',task:'任务记忆'};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let root,page,loaded=false,loading=false,items=[],sessions=[],notice='',current=null,transcript=[],task={phase:'idle'},loadEpoch=0;
  const fingerprints=new Map(),selected=new Map(),draft={kind:'task',title:'',project:'',model:'',reasoningEffort:'',instructions:''};
  const filters={session:'',days:'all',query:'',kind:'all',status:'all',sort:'recent'};
  const paging={messages:0,cards:0,history:0},pageSize={messages:24,cards:24,history:12};
  const openProjects=new Set(),projectLimits=new Map(),selectionMeta=new Map();
  let bulk=null,bulkNote='勾选会话或整个项目，即可加入蒸馏素材。';
  const projectKey=s=>s.projectId?'id:'+s.projectId:'name:'+(s.project||'未标注项目');
  const searchIndex=new WeakMap();let searchTimer,sessionLoading=false,transcriptLoading=false,selectedOnly=false;
  function pageSlice(list,key){paging[key]=Math.max(0,Math.min(paging[key],Math.ceil(list.length/pageSize[key])-1));return list.slice(paging[key]*pageSize[key],(paging[key]+1)*pageSize[key]);}
  function pager(list,key){const pages=Math.ceil(list.length/pageSize[key]);return `<div class="k-pagination"><span>共 ${list.length} ${key==='messages'?'条消息':'条记录'}</span>${pages>1?`${btn('上一页','page',`data-key="${key}" data-step="-1" ${paging[key]===0?'disabled':''}`)}<span>${paging[key]+1} / ${pages}</span>${btn('下一页','page',`data-key="${key}" data-step="1" ${paging[key]>=pages-1?'disabled':''}`)}`:''}</div>`;}
  const visibleMessages=()=>selectedOnly?transcript.filter(m=>selected.get(current)?.has(m.index)):transcript;
  let modelCatalog=null,modelsLoading=false,modelError='',previewLoading=false;
  const effortLabel=value=>({none:'无',minimal:'最低',low:'低',medium:'中',high:'高',xhigh:'更高',max:'最高',ultra:'超强'}[value]||value);
  const active=()=>['preparing','running'].includes(task.phase);
  const btn=(label,act,extra='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-kact="${act}" ${extra}>${label}</button>`;
  const kindOptions=value=>Object.entries(kinds).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('');
  const date=value=>new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
  const selectionCount=()=>[...selected.values()].reduce((n,s)=>n+s.size,0);
  const summary=(label,value,detail)=>`<div class="k-stat"><span>${label}</span><strong>${value}</strong><small>${detail}</small></div>`;
  function modelControls(){
    const models=modelCatalog?.models||[],chosen=models.find(m=>m.id===draft.model),efforts=chosen?.efforts||[];
    return `<div class="k-model-heading"><strong>模型与推理</strong>${btn(modelsLoading?'正在读取…':'重新读取','models',modelsLoading||active()?'disabled':'')}</div><label>蒸馏模型<select data-kfield="model" ${modelsLoading||!models.length||active()?'disabled':''}>${models.length?models.map(m=>`<option value="${esc(m.id)}" ${m.id===draft.model?'selected':''}>${esc(m.name)}${m.id===modelCatalog.defaultModel?' · 本机默认':''}</option>`).join(''):'<option value="">'+(modelsLoading?'读取本地模型…':'暂无本地模型')+'</option>'}</select></label><label>推理强度<select data-kfield="reasoningEffort" ${modelsLoading||!efforts.length||active()?'disabled':''}>${efforts.length?efforts.map(e=>`<option value="${esc(e.effort)}" ${e.effort===draft.reasoningEffort?'selected':''}>${esc(effortLabel(e.effort))} · ${esc(e.effort)}${e.effort===chosen.defaultEffort?'（模型默认）':''}</option>`).join(''):'<option value="">模型默认（无可选强度）</option>'}</select></label><p class="k-model-hint" role="status">${esc(modelError||modelCatalog?.warning||(modelsLoading?'正在读取本机 Codex 模型目录…':modelCatalog?`本地目录${modelCatalog.fetchedAt?' · '+date(modelCatalog.fetchedAt):''} · ${models.length} 个模型`:'读取本机 Codex 的模型与默认设置。'))}</p>`;
  }
  function drawModelControls(){const target=root?.querySelector('#k-model-controls');if(target)target.innerHTML=modelControls();syncRunControls();}
  function syncRunControls(){const run=root?.querySelector('[data-kact="preview"]');if(run){run.disabled=previewLoading||!!bulk||active()||!!task.resumable||modelsLoading||!modelCatalog||!!modelError;run.textContent=previewLoading?'正在核对素材…':active()?'蒸馏进行中…':'预览并开始蒸馏'}const cancel=root?.querySelector('[data-kact="cancel"]');if(cancel)cancel.disabled=!active();}
  async function loadModels(){if(modelsLoading)return;modelsLoading=true;modelError='';drawModelControls();try{
    const result=demo?{source:'demo',fetchedAt:null,defaultModel:'demo-balanced',defaultReasoningEffort:'medium',models:[{id:'demo-balanced',name:'均衡模型（演示）',defaultEffort:'medium',efforts:[{effort:'low'},{effort:'medium'},{effort:'high'}]},{id:'demo-deep',name:'深度模型（演示）',defaultEffort:'high',efforts:[{effort:'high'},{effort:'xhigh'}]}]}:await api.knowledgeModels();
    const oldModel=draft.model;modelCatalog=result;let chosen=result.models.find(m=>m.id===draft.model);if(!chosen){chosen=result.models.find(m=>m.id===result.defaultModel)||result.models[0];draft.model=chosen.id;draft.reasoningEffort=chosen.id===result.defaultModel?result.defaultReasoningEffort:chosen.defaultEffort;if(oldModel)toast('原选模型已不在本地目录，已改为本机默认模型，请确认。');}if(!chosen.efforts.some(e=>e.effort===draft.reasoningEffort))draft.reasoningEffort=chosen.defaultEffort||'';
  }catch(error){modelCatalog=null;modelError=error.message||'无法读取本地模型，请重试。';}finally{modelsLoading=false;drawModelControls();}}
  function header(title,sub,actions=''){return `<div class="page-heading"><div><div class="eyebrow">CODEX / KNOWLEDGE</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="actions">${actions}</div></div>`}
  async function load(){if(loading)return;loading=true;const reload=root?.querySelector('[data-kact="reload"]');if(reload){reload.disabled=true;reload.textContent='正在加载…'}try{
    if(demo){sessions=[{id:'demo',sessionId:'demo-session',title:'界面与额度优化',project:'示例项目',updatedAt:new Date().toISOString()}];items=[{id:'demo-memory',revision:1,kind:'task',title:'额度更新的验证约定',project:'示例项目',body:'保留同周期最后有效额度；新周期允许归零。界面和悬浮窗使用同一份快照。\n\n这是一条演示记忆。',origin:'manual',status:'saved',sources:[],updatedAt:new Date().toISOString()}];notice='演示数据 · 不读取真实会话，不启动 CLI。';}
    else{[items,task]=await Promise.all([api.knowledgeList(),api.knowledgeState()]);}
    loaded=true;if(page==='distill')await loadModels();
  }catch(e){notice=e.message;toast(e.message)}finally{loading=false;paint()}}
  function reconcileSessions(result){
    sessions=result.items;const ids=new Set(sessions.map(s=>s.id));let removed=0;
    for(const id of selected.keys())if(!ids.has(id)){removed+=selected.get(id).size;selected.delete(id);}
    for(const id of fingerprints.keys())if(!ids.has(id)){fingerprints.delete(id);selectionMeta.delete(id);}
    if(current&&!ids.has(current)){current=null;transcript=[];transcriptLoading=false;loadEpoch++;}
    notice=`已加载 ${result.projectCount??0} 个启用项目中的 ${sessions.length} 个未归档会话${result.missing?'，其中 '+result.missing+' 个会话在本机缺少正文':''}${result.limited?'（扫描范围受限）':''}`;
    return removed;
  }
  async function refreshSessions(){const result=await api.knowledgeSessions();const removed=reconcileSessions(result);drawSessions();drawMessages();return removed;}
  function render(next,element){page=next;root=element;paint();if(!loaded)load();else if(page==='distill')loadModels();}
  function paint(){if(!root||!['distill','memory'].includes(page)||!document.querySelector(`[data-page="${page}"].active`))return;
    root.innerHTML=page==='distill'?workbench():memory();root.onclick=click;root.oninput=input;root.onchange=change;
    if(page==='distill'){drawSessions();drawMessages();drawHistory();syncRunControls();}else drawCards();
  }
  function workbench(){return header('蒸馏工作台','从一次对话，到可复用的经验。选择素材，生成草稿，再审阅保存。',btn('刷新记录','reload'))+
    `<div class="k-stats k-workbench-stats">${summary('已选消息',selectionCount(),'只发送勾选的内容')}${summary('待审阅草稿',items.filter(x=>x.status==='draft').length,'确认后保存到记忆库')}${summary('已保存知识',items.filter(x=>x.status==='saved').length,'加密保存在本机')}${summary('当前执行方式','Codex CLI','使用本机登录账号')}</div>
    <div id="k-task" role="status" ${task.phase==='idle'?'hidden':''}>${taskStatus()}</div><div class="k-workspace"><section class="panel k-material"><div class="panel-heading"><div><span class="k-step">01</span><h2>会话素材</h2></div>${btn(sessionLoading?'正在读取…':sessions.length?'重新读取':'读取本机会话','sessions',sessionLoading?'disabled':'')}</div>
    <div class="k-filters"><input id="k-session-search" aria-label="筛选项目或会话" placeholder="搜索项目或会话" value="${esc(filters.session)}"><select id="k-days" aria-label="会话时间范围"><option value="30" ${filters.days==='30'?'selected':''}>近 30 天</option><option value="7" ${filters.days==='7'?'selected':''}>近 7 天</option><option value="all" ${filters.days==='all'?'selected':''}>全部已读取</option></select></div>
    <div class="k-bulk-status"><span id="k-bulk-note" role="status">${esc(bulkNote)}</span><button data-kact="cancel-selection" ${bulk?'':'hidden'}>取消读取</button></div><div class="k-source-layout"><nav id="k-sessions" class="k-session-list" aria-label="项目与会话"></nav><div class="k-transcript"><div id="k-current-session" class="k-transcript-title"></div><div class="k-selection-bar"><strong id="k-count">已选 ${selectionCount()} 条</strong>${btn('全选','select-all','title="选择当前会话全部可选消息，包含其他分页"')}</div><div class="k-message-tools"><span>仅展示用户与助手的正文</span><button data-kact="selected-only" aria-pressed="${selectedOnly}">${selectedOnly?'显示全部':'只看已选'}</button></div><div id="k-messages"></div></div></div><p class="help-text k-material-foot">项目勾选包含筛选外及折叠的已读取会话 · 仅启用项目、未归档 Codex 会话 · 每个会话末尾 8 MB 内最近 500 条正文</p></section>
    <section class="panel k-config"><div class="panel-heading"><div><span class="k-step">02</span><h2>生成设置</h2></div><span class="k-account-label">当前 CLI 账号</span></div><label>产物类型<select data-kfield="kind">${kindOptions(draft.kind)}</select></label><label>给这份知识起个名字<input data-kfield="title" maxlength="120" placeholder="例如：额度同步排障方法" value="${esc(draft.title)}"></label>
    <div id="k-model-controls">${modelControls()}</div><details class="k-advanced" ${draft.instructions?'open':''}><summary>项目与补充要求 <span>可选</span></summary><label>所属项目 <small>可选</small><input data-kfield="project" maxlength="500" placeholder="便于以后查找" value="${esc(draft.project)}"></label><label>补充要求<textarea data-kfield="instructions" maxlength="3000" rows="3" placeholder="例如：保留失败原因和验证方法">${esc(draft.instructions)}</textarea></label></details>
    <div class="k-run-actions">${btn(active()?'蒸馏进行中…':'预览并开始蒸馏','preview',active()?'disabled':'',true)}${btn('暂停并保存进度','cancel',active()?'':'disabled')}</div><p class="k-consent-note">支持大项目自动分批、分层整合与断点继续。调用官方模型会消耗当前账号额度。开始前可确认所选素材；生成后先保存为草稿。</p><div class="k-save-guide"><span class="k-step">03</span><div><strong>审阅，再留下</strong><p>编辑草稿、保存到记忆库，或导出 Markdown。不会自动安装 Skill 或写入 Codex 记忆目录。</p></div></div></section></div>
    <section class="panel k-history-panel"><div class="panel-heading"><h2>草稿与历史</h2><span>每份经验，都保留来源</span></div><div id="k-history"></div></section><p class="help-text" id="k-notice" role="status">${esc(notice)}</p>`;}
  function taskStatus(){const names={idle:'准备好素材后开始',preparing:'正在核对素材与检查点…',running:'正在调用 Codex CLI，请勿切换账号…',completed:'草稿已生成，可在下方编辑',paused:'任务已暂停',failed:'任务暂未完成'};
    const step=task.stage==='extracting'?`提取 ${task.batch}/${task.batches}`:task.stage==='merging'?`第 ${task.level} 层整合 · ${task.batch}/${task.batches}`:task.stage==='synthesizing'?'最终整合':'';
    return `<div class="k-checkpoint"><p class="k-task-state">${esc(names[task.phase]||task.phase)}${step?' · '+step:''}${task.message?' · '+esc(task.message):''}</p>${task.jobId?`<strong>${esc(task.title)}</strong><p>已保存 ${task.completed||0} 个检查点 · 预计最多 ${task.totalCalls} 次调用</p><small>${esc(task.model)} · ${esc(task.reasoningEffort||'默认推理强度')}</small>`:''}${task.resumable&&!active()?`<div class="actions">${btn('从断点继续','resume','',true)}${btn('放弃此任务','discard')}</div><p class="help-text">继续前会核对原素材与模型，使用本机当前账号；已经保存的批次不重复调用。</p>`:''}</div>`;}

  function drawSessions(expandMatches=false){
    const target=root.querySelector('#k-sessions');if(!target)return;
    const cutoff=filters.days==='all'?0:Date.now()-Number(filters.days)*86400000,query=filters.session.trim().toLowerCase(),groups=new Map();
    for(const session of sessions){
      if(Date.parse(session.updatedAt)<cutoff||!`${session.title} ${session.project} ${session.sessionId}`.toLowerCase().includes(query))continue;
      const key=projectKey(session);if(!groups.has(key))groups.set(key,{key,name:session.project||'未标注项目',sessions:[]});groups.get(key).sessions.push(session);
    }
    if(expandMatches&&query)for(const key of groups.keys())openProjects.add(key);
    const scroll=target.scrollTop;
    target.innerHTML=[...groups.values()].map((group,index)=>{
      const expanded=openProjects.has(group.key),limit=projectLimits.get(group.key)||5,visible=group.sessions.slice(0,limit),listId='k-project-sessions-'+index;
      return `<section class="k-project-group"><div class="k-project-row"><input class="k-source-check" type="checkbox" data-project-check="${esc(group.key)}" aria-label="选择整个项目：${esc(group.name)}" title="选择该项目全部已读取会话（含筛选外与折叠会话）"><button class="k-project-toggle" data-kact="project" data-id="${esc(group.key)}" aria-expanded="${expanded}" aria-controls="${listId}" title="${esc(group.name)}"><svg class="k-folder-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M3 7V5a2 2 0 0 1 2-2h5l3 3h6a2 2 0 0 1 2 2v2M3 7h6l2 3h10l-3 10H3a2 2 0 0 1-2-2l2-11Z"/></svg><span>${esc(group.name)}</span><svg class="k-project-chevron" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m7 4 6 6-6 6"/></svg></button></div><div id="${listId}" class="k-project-sessions" ${expanded?'':'hidden'}>${expanded?visible.map(session=>`<div class="k-session-row"><input class="k-source-check" type="checkbox" data-session-check="${esc(session.id)}" aria-label="选择会话：${esc(session.title)}" title="选择此会话全部可选正文"><button class="k-session ${session.id===current?'selected':''}" data-kact="session" data-id="${esc(session.id)}" aria-pressed="${session.id===current}" title="${esc(session.title)}"><span class="k-session-name">${esc(session.title)}</span>${session.readStatus==='not-local'?'<span class="k-missing-body" title="本机缺少正文">未就绪</span>':''}</button></div>`).join(''):''}${expanded&&group.sessions.length>limit?`<button class="k-project-more" data-kact="project-more" data-id="${esc(group.key)}">展开显示</button>`:expanded&&limit>5?`<button class="k-project-more" data-kact="project-less" data-id="${esc(group.key)}">收起列表</button>`:''}</div></section>`;
    }).join('')||`<div class="k-empty"><strong>${sessionLoading?'正在查找项目…':sessions.length?'没有匹配的项目或会话':'从一个项目开始'}</strong><p>${sessions.length?'试试其他关键词或时间范围。':'读取本机会话后，点击项目展开会话列表。'}</p></div>`;
    target.scrollTop=scroll;syncSelection();
  }
  function syncSelection(){const count=root.querySelector('#k-count');if(count)count.textContent=`已选 ${selectionCount()} 条`;const toggle=root.querySelector('[data-kact="select-all"]');if(toggle){const available=transcript.filter(m=>!m.truncated),all=available.length>0&&available.every(m=>selected.get(current)?.has(m.index));toggle.textContent=all?'取消全选':'全选';toggle.setAttribute('aria-pressed',String(all));toggle.disabled=!!bulk||transcriptLoading||!available.length;}const stat=root.querySelector('.k-workbench-stats .k-stat strong');if(stat)stat.textContent=selectionCount();syncSourceChecks();}
  function drawMessages(){const heading=root.querySelector('#k-current-session');if(heading)heading.textContent=sessions.find(s=>s.id===current)?.title||'选择会话，查看消息';const target=root.querySelector('#k-messages');if(!target)return;const list=visibleMessages();target.innerHTML=pageSlice(list,'messages').map(m=>`<label class="k-message ${selected.get(current)?.has(m.index)?'chosen':''}"><span><input type="checkbox" data-message="${m.index}" ${m.truncated?'disabled':''} ${selected.get(current)?.has(m.index)?'checked':''}>${m.role==='user'?'用户':'助手'} <small>#${m.index+1}${m.truncated?' · 内容过长，不能选用':''}</small></span><pre>${esc(m.text)}</pre></label>`).join('')||`<div class="k-empty"><span class="k-empty-symbol">${transcriptLoading?'…':'✧'}</span><strong>${transcriptLoading?'正在读取消息…':selectedOnly?'当前会话还没有选中消息':'选择值得留下的内容'}</strong><p>${current?'可以切换会话或调整消息筛选。':'先展开左侧项目并选择会话，再勾选消息。'}<br>未选择的内容不会作为素材发送。</p></div>`;if(list.length)target.insertAdjacentHTML('beforeend',pager(list,'messages'));syncSelection();}
  function rememberSelection(id,result){selectionMeta.set(id,{indices:result.messages.filter(m=>!m.truncated).map(m=>m.index),lengths:Object.fromEntries(result.messages.map(m=>[m.index,m.text.length]))});}
  function sourceState(id){const chosen=selected.get(id),available=selectionMeta.get(id)?.indices;return {any:!!chosen?.size,all:!!available?.length&&available.every(index=>chosen?.has(index)),empty:available?.length===0};}
  function syncSourceChecks(){
    const bySession=new Map(),byProject=new Map();
    for(const session of sessions){const state={...sourceState(session.id),readStatus:session.readStatus};bySession.set(session.id,state);const key=projectKey(session),group=byProject.get(key)||{any:false,all:true};group.any||=state.any;group.all&&=state.all||state.empty;byProject.set(key,group);}
    root.querySelectorAll('[data-session-check]').forEach(el=>{const state=bySession.get(el.dataset.sessionCheck)||{any:false,all:false};el.checked=state.all;el.indeterminate=state.any&&!state.all;el.disabled=!!bulk||transcriptLoading||state.readStatus==='not-local';});
    root.querySelectorAll('[data-project-check]').forEach(el=>{const state=byProject.get(el.dataset.projectCheck)||{any:false,all:false};el.checked=state.any&&state.all;el.indeterminate=state.any&&!state.all;el.disabled=!!bulk||transcriptLoading;});
    root.querySelectorAll('[data-message]').forEach(el=>el.disabled=!!bulk||!!transcript.find(m=>m.index===Number(el.dataset.message))?.truncated);
    for(const selector of ['#k-session-search','#k-days','[data-kact="sessions"]']){const el=root.querySelector(selector);if(el)el.disabled=!!bulk||sessionLoading;}
    const note=root.querySelector('#k-bulk-note');if(note)note.textContent=bulkNote;
    const cancel=root.querySelector('[data-kact="cancel-selection"]');if(cancel)cancel.hidden=!bulk;
    syncRunControls();
  }
  async function bulkSelect(node){
    if(bulk)return;
    const targets=node.dataset.projectCheck?sessions.filter(s=>projectKey(s)===node.dataset.projectCheck):sessions.filter(s=>s.id===node.dataset.sessionCheck);
    if(node.checked&&new Set([...selected.keys(),...targets.map(s=>s.id)]).size>3000){syncSelection();return toast('单任务最多选 3000 个会话，请分项目处理。');}
    if(!node.checked){for(const s of targets)selected.delete(s.id);bulkNote='已取消勾选，其他素材保持不变。';drawMessages();return;}
    const job={cancelled:false};bulk=job;const pending=new Map(),meta=new Map();let skipped=0,limited=0,missing=0,openResult,chars=0;for(const [id,set] of selected)for(const n of set)chars+=selectionMeta.get(id)?.lengths[n]||0;
    // Pending reads do not alter selection; synchronize controls only at the batch boundaries.
    syncSelection();let progressNote=root.querySelector('#k-bulk-note');
    try{
      for(const [index,s] of targets.entries()){
        if(job.cancelled)throw Error('已取消读取，原有勾选保持不变。');
        bulkNote=`正在读取会话 ${index+1}/${targets.length}…`;if(!progressNote?.isConnected)progressNote=root.querySelector('#k-bulk-note');if(progressNote)progressNote.textContent=bulkNote;
        const result=demo?{messages:[{index:0,role:'user',text:'示例会话正文',fingerprint:'demo'}]}:await api.knowledgeTranscript(s.id);
        if(job.cancelled)throw Error('已取消读取，原有勾选保持不变。');
        if(result.unavailable)throw Error('项目中有会话已归档或移除，请重新读取后勾选。');
        for(const n of selected.get(s.id)||[])chars-=selectionMeta.get(s.id)?.lengths[n]||0;
        if(result.notLocal){missing++;pending.set(s.id,new Set());meta.set(s.id,{indices:[],lengths:{},fingerprints:{}});continue;}
        const available=result.messages.filter(m=>!m.truncated);skipped+=result.messages.length-available.length;if(result.limited||result.invalidLines)limited++;
        if(s.id===current)openResult=result;
        pending.set(s.id,new Set(available.map(m=>m.index)));meta.set(s.id,{indices:available.map(m=>m.index),lengths:Object.fromEntries(available.map(m=>[m.index,m.text.length])),fingerprints:Object.fromEntries(available.map(m=>[m.index,m.fingerprint]))});
        chars+=available.reduce((sum,message)=>sum+message.text.length,0);
        if(chars>12000000)throw Error('本次选择超过单任务 1200 万字符保护上限，请分项目处理；原有选择已保留。');
      }
      for(const [id,set] of pending){if(set.size)selected.set(id,set);else selected.delete(id);selectionMeta.set(id,meta.get(id));fingerprints.set(id,meta.get(id).fingerprints);}
      if(openResult)transcript=openResult.messages;
      bulkNote=`已加入 ${[...pending.values()].filter(s=>s.size).length} 个会话；${missing?missing+' 个会话缺少本机正文；':''}${skipped?'跳过 '+skipped+' 条过长消息；':''}${limited?limited+' 个会话仅读取最近范围或有无效记录；':''}请检查素材后开始蒸馏。`;
    }catch(error){bulkNote=error.message;toast(error.message);}finally{bulk=null;drawMessages();}
  }
  function itemCard(item){return `<article class="k-card"><div class="k-card-meta"><span class="tag">${kinds[item.kind]}</span><span class="tag ${item.status==='saved'?'green':''}">${item.status==='saved'?'已保存':'草稿'}</span><small>${date(item.updatedAt)}</small></div><h3>${esc(item.title)}</h3><p class="k-project">${item.evidenceCount?item.evidenceCount+' 条完整证据 · ':''}${esc(item.project||'未指定项目')} · ${item.origin==='distill'?'来自蒸馏':'手动记录'}</p><p class="k-excerpt">${esc(item.body.slice(0,180))}</p><div class="actions">${btn('查看 / 编辑','edit',`data-id="${esc(item.id)}"`)}${btn('导出 MD','export',`data-id="${esc(item.id)}"`)}${btn('删除','delete',`data-id="${esc(item.id)}"`)}</div></article>`}
  function drawHistory(){const target=root.querySelector('#k-history');if(target){const list=items.filter(x=>x.origin==='distill');target.innerHTML=`<div class="k-card-grid">${pageSlice(list,'history').map(itemCard).join('')||'<div class="k-empty"><strong>第一份经验，等待整理</strong><p>生成的草稿会出现在这里，可编辑、保存并导出。</p></div>'}</div>${pager(list,'history')}`;}}
  function memory(){return header('记忆库','让项目约定、工作偏好与可复用方法，有据可查。',btn('刷新','reload')+btn('新增条目','new','',true))+
    `<div class="k-stats">${summary('全部条目',items.length,'草稿与已保存内容')}${summary('个人偏好',items.filter(x=>x.kind==='profile').length,'明确表达的习惯')}${summary('任务记忆',items.filter(x=>x.kind==='task').length,'背景、约定与决策')}${summary('可复用方法',items.filter(x=>['skill','workflow','prompt'].includes(x.kind)).length,'Skill / 工作流 / 提示词')}</div>
    <div class="k-library-note"><strong>你的本机知识空间</strong><span>保存项目约定与可复用方法，导出后用于新会话。Codex 不会自动加载这里的内容。</span></div>
    <div class="k-filters k-library-filters"><input id="k-query" aria-label="搜索记忆" placeholder="搜索标题、正文、项目或来源" value="${esc(filters.query)}"><select id="k-kind" aria-label="记忆类型"><option value="all">全部类型</option>${kindOptions(filters.kind)}</select><select id="k-status" aria-label="保存状态"><option value="all">全部状态</option><option value="saved" ${filters.status==='saved'?'selected':''}>已保存</option><option value="draft" ${filters.status==='draft'?'selected':''}>草稿</option></select><select id="k-sort" aria-label="记忆排序"><option value="recent" ${filters.sort==='recent'?'selected':''}>最近更新</option><option value="title" ${filters.sort==='title'?'selected':''}>按标题排序</option></select></div><div id="k-cards" class="k-card-grid"></div><p class="help-text">${esc(notice)}</p>`;}
  function drawCards(){const target=root.querySelector('#k-cards');if(!target)return;const query=filters.query.trim().toLowerCase();const list=items.filter(x=>{if(!searchIndex.has(x))searchIndex.set(x,`${x.title} ${x.body} ${x.project} ${JSON.stringify(x.sources)}`.toLowerCase());return (filters.kind==='all'||x.kind===filters.kind)&&(filters.status==='all'||x.status===filters.status)&&searchIndex.get(x).includes(query)}).sort((a,b)=>filters.sort==='title'?a.title.localeCompare(b.title,'zh-CN'):Date.parse(b.updatedAt)-Date.parse(a.updatedAt));target.innerHTML=pageSlice(list,'cards').map(itemCard).join('')||`<div class="panel k-empty"><span class="k-empty-symbol">◇</span><strong>${items.length?'没有找到匹配的知识':'让有用的经验留下来'}</strong><p>${items.length?'调整筛选条件，或清空搜索后重试。':'手动记下项目约定，或从会话蒸馏第一份草稿。'}</p>${btn(items.length?'清除筛选':'新增第一条记忆',items.length?'reset-filters':'new','',true)}</div>`;target.insertAdjacentHTML('beforeend',pager(list,'cards'));}
  function input(e){const key=e.target.dataset.kfield;if(key){if(!['model','reasoningEffort'].includes(key))draft[key]=e.target.value;return;}if(e.target.id==='k-session-search'){filters.session=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>drawSessions(true),120)}if(e.target.id==='k-query'){filters.query=e.target.value;paging.cards=0;clearTimeout(searchTimer);searchTimer=setTimeout(drawCards,120)}}
  function change(e){if(e.target.dataset.sessionCheck||e.target.dataset.projectCheck){bulkSelect(e.target).catch(error=>toast(error.message));return;}if(bulk&&e.target.dataset.message!==undefined){syncSelection();return;}if(e.target.dataset.message!==undefined){const set=selected.get(current)||new Set();const n=Number(e.target.dataset.message);if(e.target.checked){if((!selected.has(current)&&selected.size>=3000)){e.target.checked=false;toast('单任务最多选择 3000 个会话。');return;}set.add(n)}else set.delete(n);if(set.size)selected.set(current,set);else selected.delete(current);e.target.closest('.k-message').classList.toggle('chosen',e.target.checked);syncSelection();if(selectedOnly)drawMessages();}
    if(e.target.id==='k-days'){filters.days=e.target.value;drawSessions()}if(e.target.id==='k-kind'){filters.kind=e.target.value;paging.cards=0;drawCards()}if(e.target.id==='k-status'){filters.status=e.target.value;paging.cards=0;drawCards()}if(e.target.id==='k-sort'){filters.sort=e.target.value;paging.cards=0;drawCards()}if(e.target.dataset.kfield){const key=e.target.dataset.kfield;draft[key]=e.target.value;if(key==='model'){const chosen=modelCatalog?.models.find(m=>m.id===draft.model);draft.reasoningEffort=chosen?.defaultEffort||'';drawModelControls();}}
  }
  function dialog(title,body,footer,handler){document.querySelector('#knowledge-dialog')?.remove();const el=document.createElement('dialog');el.id='knowledge-dialog';el.className='k-dialog';el.innerHTML=`<div class="modal-header"><h2>${esc(title)}</h2><button class="close-btn" data-close aria-label="关闭">×</button></div>${body}<div class="modal-actions">${footer}</div>`;document.body.append(el);el.onclick=e=>{if(e.target.closest('[data-close]')){el.close();el.remove();}};el.onclose=()=>el.remove();el.addEventListener('click',e=>{const action=e.target.closest('[data-dialog-action]')?.dataset.dialogAction;if(action&&!el.dataset.pending){el.dataset.pending='1';el.querySelectorAll('button').forEach(b=>b.disabled=true);Promise.resolve(handler(action,el)).catch(e=>toast(e.message)).finally(()=>{delete el.dataset.pending;el.querySelectorAll('button').forEach(b=>b.disabled=false)})}});el.showModal();return el;}
  function edit(item){dialog(item.id?'编辑条目':'新增记忆',`<div class="k-editor"><label>标题<input name="title" maxlength="120" value="${esc(item.title)}"></label><div class="k-filters"><label>类型<select name="kind">${kindOptions(item.kind)}</select></label><label>项目<input name="project" maxlength="500" value="${esc(item.project)}"></label></div><label>正文（Markdown）<textarea name="body" rows="15" maxlength="80000">${esc(item.body)}</textarea></label><p class="help-text">来源：${esc((item.sources||[]).map(s=>`${s.title} / ${s.sessionId} / 消息 ${s.messages.map(n=>n+1).join(', ')}`).join('；')||'手动记录')}</p></div>`,`<button class="btn" data-close>取消</button><button class="btn" data-dialog-action="draft">保存草稿</button><button class="btn primary" data-dialog-action="saved">保存到记忆库</button>`,async(status,el)=>{const get=name=>el.querySelector(`[name="${name}"]`).value;const value={...item,title:get('title'),body:get('body'),kind:get('kind'),project:get('project'),status};if(demo){value.id=value.id||'demo-'+Date.now();value.updatedAt=new Date().toISOString();value.origin=value.origin||'manual';items=items.filter(x=>x.id!==value.id);items.unshift(value)}else{await api.knowledgeSave(value);items=await api.knowledgeList()}el.close();el.remove();paint();toast('已保存到本机知识库')});}
  async function click(e){const node=e.target.closest('[data-kact]');if(!node)return;const action=node.dataset.kact,id=node.dataset.id;
    if(action==='preview'&&previewLoading)return;
    try{
      if(['project','project-more','project-less'].includes(action)){if(action==='project'){if(openProjects.has(id))openProjects.delete(id);else openProjects.add(id);}else projectLimits.set(id,action==='project-less'?5:(projectLimits.get(id)||5)+20);drawSessions();const replacement=[...root.querySelectorAll('[data-kact]')].find(el=>el.dataset.kact===action&&el.dataset.id===id)||[...root.querySelectorAll('[data-kact=project]')].find(el=>el.dataset.id===id);replacement?.focus({preventScroll:true});return;}
      if(action==='cancel-selection'){if(bulk)bulk.cancelled=true;return;}
      if(bulk&&['sessions','reload','session','select-all','preview'].includes(action))return;
      if(action==='models'){await loadModels();return}
      if(action==='page'){paging[node.dataset.key]+=Number(node.dataset.step);({messages:drawMessages,cards:drawCards,history:drawHistory})[node.dataset.key]();if(node.dataset.key==='messages')root.querySelector('.k-transcript').scrollTop=0;return}
      if(action==='selected-only'){selectedOnly=!selectedOnly;paging.messages=0;node.setAttribute('aria-pressed',String(selectedOnly));node.textContent=selectedOnly?'显示全部':'只看已选';drawMessages();return}
      if(action==='reset-filters'){Object.assign(filters,{query:'',kind:'all',status:'all',sort:'recent'});paging.cards=0;paint();return}
      if(action==='reload'){await load();return}
      if(action==='sessions'){if(sessionLoading)return;if(!demo){sessionLoading=true;node.disabled=true;node.textContent='正在读取…';const result=await api.knowledgeSessions();reconcileSessions(result);}paint();return}
      if(action==='session'){current=id;transcript=[];paging.messages=0;transcriptLoading=true;drawSessions();drawMessages();const epoch=++loadEpoch;const result=demo?{messages:[{index:0,role:'user',text:'请保留同周期最后有效的周额度。'},{index:1,role:'assistant',text:'应同时验证主界面、悬浮窗和日志轮换。新周期重置允许显示 100%。'}]}:await api.knowledgeTranscript(id);if(epoch!==loadEpoch)return;transcriptLoading=false;if(result.unavailable){sessions=sessions.filter(s=>s.id!==id);selected.delete(id);fingerprints.delete(id);current=null;transcript=[];drawSessions();drawMessages();await refreshSessions();return;}if(result.notLocal){transcript=[];drawMessages();return toast('此会话已列出，但本机缺少正文。请确认会话文件后重新读取。');}transcript=result.messages;const nextFingerprints=Object.fromEntries(transcript.map(m=>[m.index,m.fingerprint])),previous=fingerprints.get(id),set=selected.get(id);let removed=0;if(set&&previous){for(const index of set)if(previous[index]!==nextFingerprints[index]||!Object.hasOwn(nextFingerprints,index)){set.delete(index);removed++;}if(!set.size)selected.delete(id);}if(removed)toast('部分已选消息发生变化，已取消勾选，请重新审阅。');fingerprints.set(id,nextFingerprints);rememberSelection(id,result);drawMessages();if(result.windowed)toast('大会话按末尾 8 MB 读取，展示其中最近 500 条完整正文；消息序号以本次读取片段为准。');else if(result.limited||result.invalidLines)toast('仅展示最近 500 条消息；部分记录可能不完整。');return}
      if(action==='select-all'){if(!current)return;const available=transcript.filter(m=>!m.truncated),set=selected.get(current)||new Set();const all=available.length&&available.every(m=>set.has(m.index));if(all){selected.delete(current);}else{if(!selected.has(current)&&selected.size>=3000)return toast('单任务最多选择 3000 个会话。');if(available.length)selected.set(current,new Set(available.map(m=>m.index)));}drawMessages();return}
      if(action==='cancel'){if(!demo)await api.knowledgeCancel();return}
      if(action==='resume'){dialog('继续蒸馏任务',`<p>继续「${esc(task.title)}」，使用本机当前登录账号和原模型 ${esc(task.model)} / ${esc(task.reasoningEffort||'默认')}，会继续消耗账号额度。已保存 ${task.completed||0} 个检查点；未保存的调用可能需要重试。</p>`,`<button class="btn" data-close>返回</button><button class="btn primary" data-dialog-action="resume">确认继续</button>`,async(_,el)=>{task=await api.knowledgeResume();el.close();paint()});return;}
      if(action==='discard'){dialog('放弃未完成任务',`<p>删除「${esc(task.title)}」的恢复记录和中间结果。已保存的草稿与原始会话保持不变。</p>`,`<button class="btn" data-close>返回</button><button class="btn danger" data-dialog-action="discard">确认放弃</button>`,async(_,el)=>{task=await api.knowledgeDiscard();el.close();paint()});return;}

      if(action==='preview'){
        if(demo)return toast('演示模式不会调用 CLI；请在桌面应用中使用。');if(modelsLoading||!modelCatalog||modelError)return toast('请先读取本地可用模型。');if(!draft.title.trim()||!selectionCount())return toast('请填写标题并选择消息。');
        previewLoading=true;syncRunControls();try{
        if(await refreshSessions())return toast('已自动移除归档或不可用会话，请确认剩余素材。');
        const selection=[...selected].filter(([,s])=>s.size).map(([id,s])=>({id,messages:[...s].sort((a,b)=>a-b),fingerprints:fingerprints.get(id)}));const request={...draft,selection},sourceTitles=new Map(sessions.map(s=>[s.id,s.title]));
        const plan=await api.knowledgePreview(request);
        dialog('确认发送所选素材',`<p>将使用本机当前登录的 Codex 账号，把 ${selection.length} 个会话的 ${selection.reduce((count,s)=>count+s.messages.length,0)} 条消息交给官方模型，生成「${esc(kinds[request.kind])}」。会消耗该账号额度。</p><p class="help-text">本次确认使用预览时的配置与素材：${esc(request.title)}。工作台后续修改不会改变本次请求。</p><p class="k-call-plan">所选约 ${Math.ceil(plan.chars/1000)} 千字符，将自动分 ${plan.batches} 批提取，最多 ${plan.levels} 层整合、${plan.calls} 次模型调用（保守估计）。每批完成后加密保存检查点，可暂停、重启后继续；失败不自动重试。</p><div class="k-confirm-model"><strong>${esc(request.model)}</strong><span>推理强度：${esc(request.reasoningEffort?effortLabel(request.reasoningEffort)+' · '+request.reasoningEffort:'模型默认')}</span></div><div class="k-callout">常见令牌会尝试遮盖，但不能保证识别所有敏感内容。请先检查已勾选的正文。未选择的消息、工具输出和账号凭据不会作为素材发送。</div><ul>${selection.map(s=>`<li>${esc(sourceTitles.get(s.id))}：${s.messages.length} 条消息</li>`).join('')}</ul>`,`<button class="btn" data-close>返回检查</button><button class="btn primary" data-dialog-action="start">确认并开始</button>`,async(_,el)=>{el.querySelector('[data-dialog-action]').disabled=true;try{task=await api.knowledgeStart(request);el.close();el.remove();paint()}catch(e){el.querySelector('[data-dialog-action]').disabled=false;throw e}});return;
        }finally{previewLoading=false;syncRunControls();}
      }
      if(action==='new')return edit({title:'',body:'',project:'',kind:'task',sources:[]});
      const item=items.find(x=>x.id===id);if(!item)return;
      if(action==='edit')return edit(item);
      if(action==='export'){if(demo)return toast('演示模式不导出文件。');if(await api.knowledgeExport(id))toast('已导出 Markdown');return}
      if(action==='delete')dialog('删除条目',`<p>删除「${esc(item.title)}」？此操作不会删除原始会话或已导出的文件。</p>`,`<button class="btn" data-close>取消</button><button class="btn danger" data-dialog-action="delete">删除</button>`,async(_,el)=>{if(demo)items=items.filter(x=>x.id!==id);else{await api.knowledgeRemove(id,item.revision);items=await api.knowledgeList()}el.close();el.remove();paint()});
    }catch(error){toast(error.message);if(action==='session'&&id===current){transcriptLoading=false;drawMessages()}if(action==='sessions'){notice=error.message;const el=root.querySelector('#k-notice');if(el)el.textContent=notice}}finally{node.disabled=false;if(action==='preview')syncRunControls();if(action==='sessions'){sessionLoading=false;const el=root.querySelector('[data-kact="sessions"]');if(el){el.disabled=false;el.textContent=sessions.length?'重新读取':'读取本机会话'}}}
  }
  async function update(event){task=event;if(['completed','failed','cancelled','paused'].includes(event.phase)){try{if(!demo)items=await api.knowledgeList();paint();toast(event.phase==='completed'?'蒸馏完成，草稿已加密保存':event.message||'任务已暂停，进度已保存')}catch(e){toast(e.message)}}else{const status=root?.querySelector('#k-task');if(status){status.hidden=task.phase==='idle';status.innerHTML=taskStatus();}drawModelControls();}}
  return {render,update};
};
