'use strict';
window.createKnowledgeUI=({api,demo,toast})=>{
  const kinds={skill:'Skill',workflow:'工作流',prompt:'提示词',profile:'个人偏好',task:'任务记忆'};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let root,page,loaded=false,loading=false,items=[],sessions=[],notice='',current=null,transcript=[],task={phase:'idle'},editor=null,loadEpoch=0;
  const fingerprints=new Map(),selected=new Map(),draft={kind:'task',title:'',project:'',model:'',instructions:''};
  const filters={session:'',days:'30',query:'',kind:'all',status:'all'};
  const active=()=>['preparing','running'].includes(task.phase);
  const btn=(label,act,extra='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-kact="${act}" ${extra}>${label}</button>`;
  const kindOptions=value=>Object.entries(kinds).map(([k,v])=>`<option value="${k}" ${k===value?'selected':''}>${v}</option>`).join('');
  const date=value=>new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
  const selectionCount=()=>[...selected.values()].reduce((n,s)=>n+s.size,0);
  const summary=(label,value,detail)=>`<div class="k-stat"><span>${label}</span><strong>${value}</strong><small>${detail}</small></div>`;
  function header(title,sub,actions=''){return `<div class="page-heading"><div><div class="eyebrow">LOCAL KNOWLEDGE · CODEX</div><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="actions">${actions}</div></div>`}
  async function load(){if(loading)return;loading=true;try{
    if(demo){sessions=[{id:'demo',sessionId:'demo-session',title:'界面与额度优化',project:'示例项目',updatedAt:new Date().toISOString()}];items=[{id:'demo-memory',revision:1,kind:'task',title:'额度更新的验证约定',project:'示例项目',body:'保留同周期最后有效额度；新周期允许归零。界面和悬浮窗使用同一份快照。\n\n这是一条演示记忆。',origin:'manual',status:'saved',sources:[],updatedAt:new Date().toISOString()}];notice='演示数据 · 不读取真实会话，不启动 CLI。';}
    else{[items,task]=await Promise.all([api.knowledgeList(),api.knowledgeState()]);}
    loaded=true;
  }catch(e){notice=e.message;toast(e.message)}finally{loading=false;paint()}}
  function render(next,element){page=next;root=element;paint();if(!loaded)load();}
  function paint(){if(!root||!['distill','memory'].includes(page)||!document.querySelector(`[data-page="${page}"].active`))return;
    root.innerHTML=page==='distill'?workbench():memory();root.onclick=click;root.oninput=input;root.onchange=change;
    if(page==='distill'){drawSessions();drawMessages();drawHistory();}else drawCards();
  }
  function workbench(){return header('蒸馏工作台','把选中的会话经验，整理成下一次能直接使用的知识。',btn('刷新记录','reload'))+
    `<div class="k-stats">${summary('已选消息',selectionCount(),'只发送你选择的片段')}${summary('蒸馏草稿',items.filter(x=>x.status==='draft').length,'审阅后再保存')}${summary('已保存',items.filter(x=>x.status==='saved').length,'加密保存在本机')}${summary('执行方式','Codex CLI','使用本机当前登录账号')}</div>
    <div class="k-workspace"><section class="panel k-material"><div class="panel-heading"><h2>01 / 选择素材</h2>${btn('读取本机会话','sessions')}</div><p class="help-text">读取最近 300 个 JSONL 会话。按项目或时间筛选，点击会话后选择具体消息；不读取工具输出。</p>
    <div class="k-filters"><input id="k-session-search" aria-label="筛选项目或会话" placeholder="搜索项目或会话 ID" value="${esc(filters.session)}"><select id="k-days" aria-label="会话时间范围"><option value="30" ${filters.days==='30'?'selected':''}>近 30 天</option><option value="7" ${filters.days==='7'?'selected':''}>近 7 天</option><option value="all" ${filters.days==='all'?'selected':''}>全部已读取</option></select></div>
    <div class="k-source-layout"><div id="k-sessions" class="k-session-list"></div><div class="k-transcript"><div class="k-selection-bar"><strong id="k-count">已选 ${selectionCount()} 条</strong>${btn('全选本会话','select-all')}${btn('清空全部','clear')}</div><div id="k-messages"></div></div></div></section>
    <section class="panel k-config"><h2>02 / 配置产物</h2><label>产物类型<select data-kfield="kind">${kindOptions(draft.kind)}</select></label><label>标题<input data-kfield="title" maxlength="120" placeholder="例如：桌面端额度同步排障方法" value="${esc(draft.title)}"></label><label>所属项目<input data-kfield="project" maxlength="500" placeholder="可选，用于记忆分类" value="${esc(draft.project)}"></label><label>模型<input data-kfield="model" maxlength="80" placeholder="留空使用 CLI 默认模型" value="${esc(draft.model)}"></label><label>补充要求<textarea data-kfield="instructions" maxlength="3000" rows="4" placeholder="例如：保留失败原因、验证方法和适用边界">${esc(draft.instructions)}</textarea></label>
    <div class="k-callout">通过当前登录账号调用官方模型，会消耗相应额度，并非离线生成。仅发送所选片段与配置要求。不会自动安装 Skill 或写入 Codex 记忆目录。</div><div id="k-task" role="status">${taskStatus()}</div><div class="k-run-actions">${btn(active()?'蒸馏进行中…':'预览并开始蒸馏','preview',active()?'disabled':'',true)}${btn('取消任务','cancel',active()?'':'disabled')}</div></section></div>
    <section class="panel"><div class="panel-heading"><h2>03 / 草稿与历史</h2><span>生成不等于确认 · 编辑后保存或导出</span></div><div id="k-history"></div></section><p class="help-text" id="k-notice">${esc(notice)}</p>`;}
  function taskStatus(){const names={idle:'准备好素材后开始',preparing:'正在检查素材与当前账号…',running:'正在调用 Codex CLI，请勿切换账号…',completed:'草稿已生成，可在下方编辑',cancelled:'任务已取消',failed:'生成失败'};return `<p class="k-task-state">${esc(names[task.phase]||task.phase)}${task.message?' · '+esc(task.message):''}</p>`}
  function drawSessions(){const target=root.querySelector('#k-sessions');if(!target)return;const cutoff=filters.days==='all'?0:Date.now()-Number(filters.days)*86400000;const list=sessions.filter(x=>Date.parse(x.updatedAt)>=cutoff&&`${x.title} ${x.project} ${x.sessionId}`.toLowerCase().includes(filters.session.toLowerCase()));target.innerHTML=list.map(s=>`<button class="k-session ${s.id===current?'selected':''}" data-kact="session" data-id="${esc(s.id)}"><strong>${esc(s.title)}</strong><span>${esc(s.project||'未标注项目')}</span><small>${date(s.updatedAt)} · 已选 ${selected.get(s.id)?.size||0} 条</small></button>`).join('')||'<div class="k-empty">点击“读取本机会话”加载素材，或调整筛选条件。</div>';}
  function drawMessages(){const target=root.querySelector('#k-messages');if(!target)return;target.innerHTML=transcript.map(m=>`<label class="k-message ${selected.get(current)?.has(m.index)?'chosen':''}"><span><input type="checkbox" data-message="${m.index}" ${m.truncated?'disabled':''} ${selected.get(current)?.has(m.index)?'checked':''}>${m.role==='user'?'用户':'助手'} · #${m.index+1}${m.truncated?' · 内容过长，不能选用':''}</span><pre>${esc(m.text)}</pre></label>`).join('')||'<div class="k-empty">选择左侧会话，然后勾选要整理的消息。</div>';const count=root.querySelector('#k-count');if(count)count.textContent=`已选 ${selectionCount()} 条`;}
  function itemCard(item){return `<article class="k-card"><div class="k-card-meta"><span class="tag">${kinds[item.kind]}</span><span class="tag ${item.status==='saved'?'green':''}">${item.status==='saved'?'已保存':'草稿'}</span><small>${date(item.updatedAt)}</small></div><h3>${esc(item.title)}</h3><p class="k-project">${esc(item.project||'未指定项目')} · ${item.origin==='distill'?'来自蒸馏':'手动记录'}</p><p class="k-excerpt">${esc(item.body.slice(0,180))}</p><div class="actions">${btn('查看 / 编辑','edit',`data-id="${esc(item.id)}"`)}${btn('导出 MD','export',`data-id="${esc(item.id)}"`)}${btn('删除','delete',`data-id="${esc(item.id)}"`)}</div></article>`}
  function drawHistory(){const target=root.querySelector('#k-history');if(target)target.innerHTML=`<div class="k-card-grid">${items.filter(x=>x.origin==='distill').map(itemCard).join('')||'<div class="k-empty">还没有蒸馏结果。选取少量有价值的片段，生成第一份草稿。</div>'}</div>`}
  function memory(){return header('记忆库','让项目约定、工作偏好与可复用方法，有据可查。',btn('刷新','reload')+btn('新增条目','new','',true))+
    `<div class="k-stats">${summary('全部条目',items.length,'草稿与已保存内容')}${summary('个人偏好',items.filter(x=>x.kind==='profile').length,'明确表达的习惯')}${summary('任务记忆',items.filter(x=>x.kind==='task').length,'背景、约定与决策')}${summary('可复用方法',items.filter(x=>['skill','workflow','prompt'].includes(x.kind)).length,'Skill / 工作流 / 提示词')}</div>
    <div class="k-callout">记忆保存在本工具内。导出后可作为下次会话的上下文；这里保存成功不代表 Codex 已自动加载。账号切换不会删除知识库。</div>
    <div class="k-filters k-library-filters"><input id="k-query" aria-label="搜索记忆" placeholder="搜索标题、正文、项目或来源" value="${esc(filters.query)}"><select id="k-kind" aria-label="记忆类型"><option value="all">全部类型</option>${kindOptions(filters.kind)}</select><select id="k-status" aria-label="保存状态"><option value="all">全部状态</option><option value="saved" ${filters.status==='saved'?'selected':''}>已保存</option><option value="draft" ${filters.status==='draft'?'selected':''}>草稿</option></select></div><div id="k-cards" class="k-card-grid"></div><p class="help-text">${esc(notice)}</p>`;}
  function drawCards(){const target=root.querySelector('#k-cards');if(!target)return;const list=items.filter(x=>(filters.kind==='all'||x.kind===filters.kind)&&(filters.status==='all'||x.status===filters.status)&&`${x.title} ${x.body} ${x.project} ${JSON.stringify(x.sources)}`.toLowerCase().includes(filters.query.toLowerCase()));target.innerHTML=list.map(itemCard).join('')||'<div class="panel k-empty">还没有匹配的条目。可以手动新增，或从蒸馏工作台生成草稿。</div>';}
  function input(e){const key=e.target.dataset.kfield;if(key){draft[key]=e.target.value;return;}if(e.target.id==='k-session-search'){filters.session=e.target.value;drawSessions()}if(e.target.id==='k-query'){filters.query=e.target.value;drawCards()}}
  function change(e){if(e.target.dataset.message!==undefined){const set=selected.get(current)||new Set();const n=Number(e.target.dataset.message);if(e.target.checked)set.add(n);else set.delete(n);if(set.size)selected.set(current,set);else selected.delete(current);drawMessages();drawSessions();const stat=root.querySelector('.k-stat strong');if(stat)stat.textContent=selectionCount();}
    if(e.target.id==='k-days'){filters.days=e.target.value;drawSessions()}if(e.target.id==='k-kind'){filters.kind=e.target.value;drawCards()}if(e.target.id==='k-status'){filters.status=e.target.value;drawCards()}if(e.target.dataset.kfield)draft[e.target.dataset.kfield]=e.target.value;
  }
  function dialog(title,body,footer,handler){document.querySelector('#knowledge-dialog')?.remove();const el=document.createElement('dialog');el.id='knowledge-dialog';el.className='k-dialog';el.innerHTML=`<div class="modal-header"><h2>${esc(title)}</h2><button class="close-btn" data-close aria-label="关闭">×</button></div>${body}<div class="modal-actions">${footer}</div>`;document.body.append(el);el.onclick=e=>{if(e.target.closest('[data-close]'))el.close();};el.onclose=()=>{editor=null;el.remove()};el.addEventListener('click',e=>{const action=e.target.closest('[data-dialog-action]')?.dataset.dialogAction;if(action)Promise.resolve(handler(action,el)).catch(e=>toast(e.message))});el.showModal();return el;}
  function edit(item){editor=item;dialog(item.id?'编辑条目':'新增记忆',`<div class="k-editor"><label>标题<input name="title" maxlength="120" value="${esc(item.title)}"></label><div class="k-filters"><label>类型<select name="kind">${kindOptions(item.kind)}</select></label><label>项目<input name="project" maxlength="500" value="${esc(item.project)}"></label></div><label>正文（Markdown）<textarea name="body" rows="15" maxlength="80000">${esc(item.body)}</textarea></label><p class="help-text">来源：${esc((item.sources||[]).map(s=>`${s.title} / ${s.sessionId} / 消息 ${s.messages.map(n=>n+1).join(', ')}`).join('；')||'手动记录')}</p></div>`,`<button class="btn" data-close>取消</button><button class="btn" data-dialog-action="draft">保存草稿</button><button class="btn primary" data-dialog-action="saved">保存到记忆库</button>`,async(status,el)=>{const get=name=>el.querySelector(`[name="${name}"]`).value;const value={...editor,title:get('title'),body:get('body'),kind:get('kind'),project:get('project'),status};if(demo){value.id=value.id||'demo-'+Date.now();value.updatedAt=new Date().toISOString();value.origin=value.origin||'manual';items=items.filter(x=>x.id!==value.id);items.unshift(value)}else{await api.knowledgeSave(value);items=await api.knowledgeList()}el.close();paint();toast('已保存到本机知识库')});}
  async function click(e){const node=e.target.closest('[data-kact]');if(!node)return;const action=node.dataset.kact,id=node.dataset.id;
    try{
      if(action==='reload'){await load();return}
      if(action==='sessions'){if(!demo){node.disabled=true;const result=await api.knowledgeSessions();sessions=result.items;notice=`已加载 ${sessions.length} 个会话${result.skipped?'，跳过 '+result.skipped+' 个不可读或过大文件':''}${result.limited?'（扫描范围受限）':''}`;}paint();return}
      if(action==='session'){current=id;transcript=[];drawSessions();drawMessages();const epoch=++loadEpoch;const result=demo?{messages:[{index:0,role:'user',text:'请保留同周期最后有效的周额度。'},{index:1,role:'assistant',text:'应同时验证主界面、悬浮窗和日志轮换。新周期重置允许显示 100%。'}]}:await api.knowledgeTranscript(id);if(epoch!==loadEpoch)return;transcript=result.messages;fingerprints.set(id,Object.fromEntries(transcript.map(m=>[m.index,m.fingerprint])));drawMessages();if(result.limited||result.invalidLines)toast('仅展示最近 500 条消息；部分记录可能不完整。');return}
      if(action==='select-all'){if(current)selected.set(current,new Set(transcript.filter(m=>!m.truncated).map(m=>m.index)));paint();return}
      if(action==='clear'){selected.clear();paint();return}
      if(action==='cancel'){if(!demo)await api.knowledgeCancel();return}
      if(action==='preview'){
        if(demo)return toast('演示模式不会调用 CLI；请在桌面应用中使用。');if(!draft.title.trim()||!selectionCount())return toast('请填写标题并选择消息。');
        const selection=[...selected].filter(([,s])=>s.size).map(([id,s])=>({id,messages:[...s].sort((a,b)=>a-b),fingerprints:fingerprints.get(id)}));const request={...draft,selection};
        dialog('确认发送所选素材',`<p>将使用本机当前登录的 Codex 账号，把 ${selectionCount()} 条消息交给官方模型，生成「${esc(kinds[draft.kind])}」。会消耗该账号额度。</p><div class="k-callout">常见令牌会尝试遮盖，但不能保证识别所有敏感内容。请先检查已勾选的正文。未选择的消息、工具输出和账号凭据不会作为素材发送。</div><ul>${selection.map(s=>`<li>${esc(sessions.find(x=>x.id===s.id)?.title)}：消息 ${s.messages.map(n=>n+1).join(', ')}</li>`).join('')}</ul>`,`<button class="btn" data-close>返回检查</button><button class="btn primary" data-dialog-action="start">确认并开始</button>`,async(_,el)=>{el.querySelector('[data-dialog-action]').disabled=true;try{task=await api.knowledgeStart(request);el.close();paint()}catch(e){el.querySelector('[data-dialog-action]').disabled=false;throw e}});return;
      }
      if(action==='new')return edit({title:'',body:'',project:'',kind:'task',sources:[]});
      const item=items.find(x=>x.id===id);if(!item)return;
      if(action==='edit')return edit(item);
      if(action==='export'){if(demo)return toast('演示模式不导出文件。');if(await api.knowledgeExport(id))toast('已导出 Markdown');return}
      if(action==='delete')dialog('删除条目',`<p>删除「${esc(item.title)}」？此操作不会删除原始会话或已导出的文件。</p>`,`<button class="btn" data-close>取消</button><button class="btn danger" data-dialog-action="delete">删除</button>`,async(_,el)=>{if(demo)items=items.filter(x=>x.id!==id);else{await api.knowledgeRemove(id,item.revision);items=await api.knowledgeList()}el.close();paint()});
    }catch(error){toast(error.message)}finally{node.disabled=false;}
  }
  async function update(event){task=event;if(['completed','failed','cancelled'].includes(event.phase)){try{if(!demo)items=await api.knowledgeList();paint();toast(event.phase==='completed'?'蒸馏完成，草稿已加密保存':event.message||'任务已取消')}catch(e){toast(e.message)}}else paint();}
  return {render,update};
};
