'use strict';
window.createSkillsUI=({api,demo,toast})=>{
  const errorText=error=>String(error?.message||error).replace(/^Error invoking remote method '[^']+': (?:Error: )?/,'');
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const translation=window.createSkillTranslation({api,demo,toast,esc,onChange:paint});
  let root,tab='library',data=null,catalog=null,query='',filter='all',repo='openai/skills',ref='HEAD',busy=false,storeLoading=false,storeEpoch=0,loaded=false,error='',selectedGroups=new Set(),cardLimit=60;
  const button=(text,action,extra='',primary=false)=>`<button class="btn ${primary?'primary':''}" data-sact="${action}" ${extra} ${busy?'disabled':''}>${text}</button>`;
  const visible=()=>root&&document.querySelector('[data-page="skills"].active');
  const demoData=()=>({revision:1,activeGroupIds:['common','daily'],managedIds:[],installed:[],history:[],warnings:[],bank:'本机技能仓库',groups:[{id:'common',name:'通用基础',skillIds:['review']},{id:'daily',name:'日常',skillIds:['design','writing']},{id:'research',name:'科研',skillIds:['research','plot']}],items:[['review','code-review','代码审阅：检查改动风险、边界与验证。',true,['common']],['design','frontend-design','构建清晰、美观且易用的前端界面。',true,['daily']],['writing','writing-workflows','整理文档、工作约定和可复用写作流程。',true,['daily']],['research','literature-review','围绕研究问题整理文献与证据。',false,['research']],['plot','scientific-visualization','制作科研图表并检查视觉表达。',false,['research']]].map(([id,name,description,enabled,groupIds])=>({id,name,description,enabled,linked:true,groupIds,managed:false})),sources:[{repo:'openai/skills',name:'OpenAI'},{repo:'anthropics/skills',name:'Anthropic'},{repo:'K-Dense-AI/claude-scientific-skills',name:'科研工具箱'}]});
  async function load(){if(busy)return;busy=true;error='';paint();try{data=demo?demoData():await api.skillsList();selectedGroups=new Set(data.activeGroupIds);loaded=true;}catch(e){error=errorText(e);}finally{busy=false;paint();}}
  function render(element){root=element;paint();if(!loaded&&!busy)load();}
  function paint(){if(!visible())return;
    root.innerHTML=`<div class="page-heading"><div><div class="eyebrow">CODEX / SKILLS</div><h1>Skills 管理</h1><p class="subtitle">把合适的能力，带进每一种工作场景。</p></div><div class="actions">${button('重新读取','reload')}${button('逛技能商店','store','',true)}</div></div>
      <div class="s-hero"><div class="s-hero-icon">◇</div><div><span class="s-eyebrow">YOUR SKILL COLLECTION</span><h2>${data?.activeGroupIds.length?esc(data.groups.filter(g=>data.activeGroupIds.includes(g.id)).map(g=>g.name).join(' + ')):'为日常与科研，准备不同的工具箱'}</h2><p>${data?.pendingRestart?'分组配置已保存。重启 Codex 后使用新的技能组合。':'统一浏览本机技能，按场景组合，再从商店补充所需能力。'}</p></div><div class="s-metrics"><span><strong>${data?.items.length??'—'}</strong>本机技能</span><span><strong>${data?.items.filter(i=>i.enabled).length??'—'}</strong>配置启用</span><span><strong>${data?.groups.length??'—'}</strong>场景分组</span></div></div>
      <div class="s-tabs" role="tablist">${[['library','技能库'],['groups','场景分组'],['store','技能商店']].map(([id,label])=>`<button role="tab" aria-selected="${tab===id}" data-sact="tab" data-id="${id}">${label}</button>`).join('')}</div>
      ${error?`<div class="s-notice" role="alert">${esc(error)}</div>`:''}${busy||storeLoading?'<div class="s-notice" role="status">正在处理，请稍候…</div>':''}
      ${translation.controls()}<div id="skills-body">${tab==='library'?library():tab==='groups'?groups():store()}</div>`;
    root.onclick=click;root.oninput=input;root.onchange=change;
  }
  function toolbar(){return `<div class="s-toolbar"><input id="s-search" type="search" placeholder="${tab==='store'?'搜索技能名称或目录':'搜索名称、说明或分组'}" aria-label="搜索技能" value="${esc(query)}">${tab==='library'?`<select id="s-filter" aria-label="筛选技能"><option value="all">全部技能</option><option value="enabled" ${filter==='enabled'?'selected':''}>配置启用</option><option value="disabled" ${filter==='disabled'?'selected':''}>未启用</option>${(data?.groups||[]).map(g=>`<option value="${g.id}" ${filter===g.id?'selected':''}>${esc(g.name)}</option>`).join('')}</select>`:''}<span id="s-results"></span></div>`;}
  function library(){return `${toolbar()}<div class="s-grid" id="s-cards">${libraryCards()}</div>${data?.warnings.length?`<details class="s-notice"><summary>${data.warnings.length} 条读取提示</summary>${data.warnings.map(w=>`<p>${esc(w)}</p>`).join('')}</details>`:''}<p class="help-text">读取本机 Skills Hub、Codex 与 .agents 技能目录；系统和插件自带技能不纳入场景切换。配置启用不代表当前已打开的任务已重新加载。</p>`;}
  function moreCards(total){return `<div class="s-more"><span>已显示 ${Math.min(cardLimit,total)} / ${total} 项</span>${total>cardLimit?button('显示更多','more-cards'):''}</div>`;}
  function libraryCards(){const items=(data?.items||[]).filter(i=>(filter==='all'||filter==='enabled'&&i.enabled||filter==='disabled'&&!i.enabled||i.groupIds.includes(filter))&&`${i.name} ${i.description} ${i.groupIds.map(id=>data.groups.find(g=>g.id===id)?.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
    return (items.slice(0,cardLimit).map(i=>`<article class="s-card"><div class="s-card-top"><span class="s-skill-mark">${esc(i.name.slice(0,1).toUpperCase())}</span><span class="s-badge ${i.enabled?'on':''}">${i.enabled?'配置启用':i.linked?'已停用':'仅入库'}</span></div><h3>${esc(i.name)}</h3><p>${esc(i.description)}</p>${translation.card(i.name.replaceAll('-',' ')+'\n'+i.description)}<div class="s-tags">${i.groupIds.map(id=>`<span>${esc(data.groups.find(g=>g.id===id)?.name)}</span>`).join('')||'<span>未分组</span>'}</div><div class="s-card-footer"><small>${i.source?esc(i.source.repo):'本机已有技能'}</small>${button('查看','detail',`data-id="${i.id}"`)}</div></article>`).join('')||`<div class="panel s-empty"><h3>${loaded?'没有匹配的技能':'正在读取技能库'}</h3><p>可以调整搜索，或前往商店安装新的技能。</p></div>`)+moreCards(items.length);}
  function groups(){return `<div class="s-section-head"><div><h2>按场景组合能力</h2><p>可同时启用多组；“切换此组”保留通用基础，并替换其他组。</p></div>${button('新建分组','new-group')}</div><div class="s-group-grid">${(data?.groups||[]).map(g=>`<article class="s-group ${selectedGroups.has(g.id)?'chosen':''}"><div class="s-group-head"><span>${g.id==='research'?'研':g.id==='daily'?'日':g.id==='common'?'通':'组'}</span><label><input type="checkbox" data-sgroup="${g.id}" ${selectedGroups.has(g.id)?'checked':''} ${busy?'disabled':''}>选择此组</label></div><h3>${esc(g.name)}</h3><p>${g.skillIds.length} 个技能${data.activeGroupIds.includes(g.id)?' · 当前配置':''}</p><div class="s-group-names">${g.skillIds.slice(0,4).map(id=>esc(data.items.find(i=>i.id===id)?.name||'已移除技能')).join(' · ')||'添加技能，构建你的场景组合'}${g.skillIds.length>4?' …':''}</div><div class="actions">${button('编辑','edit-group',`data-id="${g.id}"`)}${button('切换此组','switch-group',`data-id="${g.id}"`,true)}</div></article>`).join('')}</div><div class="s-apply-bar"><div><strong>已选 ${selectedGroups.size} 个分组</strong><p>预览会列出将启用、停用的技能。分组外且未被本工具管理的技能保持现有配置。</p></div>${button('预览并应用','apply-groups','',true)}</div>${data?.history.length?`<details class="s-history"><summary>最近操作</summary>${data.history.slice(0,10).map(h=>`<p>${esc(new Date(h.at).toLocaleString('zh-CN'))} · ${esc(h.text)}</p>`).join('')}</details>`:''}`;}
  const selectedSource=()=>(data?.sources||[]).find(source=>source.repo.toLowerCase()===repo.toLowerCase()&&(source.ref||'HEAD')===ref);
  function sourceButtons(custom){return (data?.sources||[]).filter(source=>!!source.custom===custom).map(source=>`<div class="s-source-row"><button data-sact="source" data-id="${esc(source.id||source.repo)}" aria-pressed="${selectedSource()===source}" class="${selectedSource()===source?'selected':''}"><strong>${esc(source.name)}</strong><small>${esc(source.repo)}${(source.ref||'HEAD')!=='HEAD'?' · '+esc(source.ref):''}</small></button>${custom?`<button class="s-source-manage" data-sact="edit-source" data-id="${esc(source.id)}" aria-label="管理 ${esc(source.name)}" title="编辑或移除来源">⋯</button>`:''}</div>`).join('');}
  function store(){return `<div class="s-store-layout"><aside class="s-sources"><div class="s-sources-title"><h3>发现技能</h3>${button('＋ 添加','add-source','aria-label="添加自定义来源"')}</div><div class="s-source-list">${sourceButtons(false)}</div><div class="s-sources-title s-custom-title"><h3>我的来源 <span>${data?.sources.filter(source=>source.custom).length||0}</span></h3></div><div class="s-source-list">${sourceButtons(true)||'<p class="s-source-empty">添加常用 GitHub 仓库，下次直接从这里打开。</p>'}</div><details class="s-custom-source"><summary>临时读取仓库</summary><label>GitHub 仓库<input id="s-repo" placeholder="owner/repository" value="${esc(repo)}"></label><label>分支 / Tag<input id="s-ref" placeholder="HEAD" value="${esc(ref)}"></label>${button('读取仓库','custom-source')}${button('保存为来源','save-current-source')}</details></aside><section><div class="s-store-heading"><div><h2>${esc(selectedSource()?.name||repo)}</h2><p>${esc(repo)} · ${esc(ref)}<br>${catalog?`${catalog.items.length} 个技能 · ${esc(catalog.commit?.slice(0,8)||'演示')}`:'从仓库获取真实技能目录'}</p></div><div class="actions">${selectedSource()?.custom?button('编辑来源','edit-source',`data-id="${esc(selectedSource().id)}"`):''}${button(data?.githubToken?.configured?'Token 已设置':'GitHub Token','github-token')}${button(storeLoading?'读取中…':'刷新商店','refresh-store',storeLoading?'disabled':'')}</div></div>${catalog?.notice?`<div class="s-notice" role="status">${esc(catalog.notice)}</div>`:''}${catalog?.stale?`<div class="s-notice">缓存目录 · ${esc(catalog.warning)} · 安装仍需联网</div>`:''}${toolbar()}<div class="s-grid s-store-grid" id="s-cards">${storeCards()}</div><p class="help-text">技能来源于所选 GitHub 仓库。安装前可审阅原文、许可证和文件数量；安装不会执行附带脚本。首次使用时仍需检查技能所需的工具与依赖。</p></section></div>`;}
  function storeCards(){const items=(catalog?.items||[]).filter(i=>`${i.name} ${i.folder}`.toLowerCase().includes(query.toLowerCase()));return (items.slice(0,cardLimit).map(i=>`<article class="s-card"><div class="s-card-top"><span class="s-skill-mark">${esc(i.name.slice(0,1).toUpperCase())}</span><span class="s-badge">${data?.items.some(local=>local.source?.id===i.id)?'已入库':'GitHub'}</span></div><h3>${esc(i.name)}</h3><p class="s-source-path">${esc(i.folder||'仓库根目录')}</p>${translation.card(i.name.replaceAll('-', ' '))}<div class="s-card-footer"><small>查看说明后安装</small>${button('查看与安装','preview-skill',`data-id="${i.id}"`)}</div></article>`).join('')||'<div class="panel s-empty"><h3>发现你的下一项能力</h3><p>选择左侧来源，加载技能目录；也可添加自定义 GitHub 仓库。</p></div>')+moreCards(items.length);}
  function input(e){if(e.target.id==='s-search'){query=e.target.value;cardLimit=60;root.querySelector('#s-cards').innerHTML=tab==='library'?libraryCards():storeCards();}}
  function change(e){if(e.target.id==='s-filter'){filter=e.target.value;cardLimit=60;root.querySelector('#s-cards').innerHTML=libraryCards();}if(e.target.dataset.sgroup){e.target.checked?selectedGroups.add(e.target.dataset.sgroup):selectedGroups.delete(e.target.dataset.sgroup);paint();}}
  function dialog(title,body,footer,handler){document.querySelector('#skills-dialog')?.remove();const el=document.createElement('dialog');el.id='skills-dialog';el.className='s-dialog';el.innerHTML=`<div class="modal-header"><h2>${esc(title)}</h2><button class="close-btn" data-close aria-label="关闭">×</button></div>${body}<div class="modal-actions">${footer}</div>`;document.body.append(el);el.onclick=async e=>{if(el.dataset.pending)return;const select=e.target.closest('[data-pick-all]');if(select){el.querySelectorAll('[name=skill]').forEach(input=>{input.checked=select.dataset.pickAll==='yes'});syncGroupSelection(el);return;}if(e.target.closest('[data-close]'))return el.close();const action=e.target.closest('[data-submit]')?.dataset.submit;if(!action)return;el.dataset.pending='1';el.querySelectorAll('button').forEach(b=>b.disabled=true);try{await handler(action,el)}catch(error){toast(errorText(error))}finally{delete el.dataset.pending;el.querySelectorAll('button').forEach(b=>b.disabled=false);syncGroupSelection(el);}};el.onchange=()=>syncGroupSelection(el);el.oncancel=e=>{if(el.dataset.pending)e.preventDefault()};el.onclose=()=>el.remove();el.showModal();syncGroupSelection(el);return el;}
  async function action(fn){if(busy)return;busy=true;error='';paint();try{await fn()}catch(e){error=errorText(e);toast(errorText(e))}finally{busy=false;paint();}}
  function invalidateStore(){storeEpoch++;storeLoading=false;catalog=null;error='';}
  async function readStore(force=false){
    const epoch=++storeEpoch,source={repo,ref,force};storeLoading=true;error='';paint();
    try{const value=demo?{items:[{id:'demo-skill',name:'research-notes',folder:'skills/research-notes'}],commit:'demo'}:await api.skillsCatalog(source);if(epoch===storeEpoch)catalog=value;}
    catch(e){if(epoch===storeEpoch){error=errorText(e);toast(error);}}
    finally{if(epoch===storeEpoch){storeLoading=false;paint();}}
  }
  function editGithubToken(){
    dialog('GitHub Token',`<p class="help-text">可提高 API 请求额度，减少技能目录刷新限流；不保证网络下载速度。支持公开仓库及 Token 有权访问的私有仓库。</p><p class="s-notice">${data?.githubToken?.configured?'已在本机加密保存。填写新 Token 可替换，已有值不会回显。':'尚未设置，当前使用匿名访问。'}</p><label class="s-field">Personal Access Token<input name="github-token" type="password" autocomplete="new-password" spellcheck="false" maxlength="255" placeholder="粘贴 GitHub Personal Access Token"></label><p class="help-text">私有仓库请授权对应仓库的 Contents 只读权限，无需写入权限。Token 只在本机加密保存，仅发送到 GitHub API，不随分组或来源导出。</p>`,`<button class="btn" data-close>取消</button>${data?.githubToken?.configured?'<button class="btn danger" data-submit="remove-token">移除 Token</button>':''}<button class="btn primary" data-submit="save-token">保存并刷新</button>`,async(act,el)=>{
      if(demo)return toast('演示模式不保存 Token。');
      const input=el.querySelector('[name=github-token]');const value=input.value;input.value='';
      data=act==='remove-token'?await api.skillsRemoveToken():await api.skillsSaveToken({value});invalidateStore();el.close();paint();toast(act==='remove-token'?'Token 已移除，恢复匿名访问。':'Token 已加密保存，正在刷新目录。');await readStore(true);
    });
  }
  function editSource(id,prefill=false){
    const source=data.sources.find(source=>source.id===id&&source.custom)||{name:'',repo:prefill?repo:'',ref:prefill?ref:'HEAD'};
    dialog(id?'编辑自定义来源':'添加自定义来源',`<p class="help-text">保存后显示在左侧“我的来源”，重启应用也会保留。</p><label class="s-field">来源名称<input name="source-name" maxlength="40" placeholder="例如：我的科研技能" value="${esc(source.name)}"></label><label class="s-field">GitHub 仓库<input name="source-repo" placeholder="owner/repository 或 https://github.com/owner/repository" value="${esc(source.repo)}"></label><label class="s-field">分支 / Tag / 提交<input name="source-ref" maxlength="150" placeholder="HEAD（默认分支）" value="${esc(source.ref)}"></label><p class="help-text">保存来源不会安装或启用技能；移除来源也不会卸载已经安装的技能。私有仓库需设置有读取权限的 GitHub Token。</p>`,`<button class="btn" data-close>取消</button>${id?'<button class="btn danger" data-submit="remove-source">移除来源</button>':''}<button class="btn primary" data-submit="save-source">保存来源</button>`,async(act,el)=>{
      if(demo)return toast('演示模式不修改本机来源。');
      if(act==='remove-source'){
        const removingCurrent=selectedSource()?.id===id;data=await api.skillsRemoveSource({id,revision:data.revision});el.close();if(removingCurrent){invalidateStore();repo=data.sources[0].repo;ref=data.sources[0].ref||'HEAD';query='';cardLimit=60;}paint();toast('已移除来源，已安装技能保持不变。');return;
      }
      const name=el.querySelector('[name=source-name]').value.trim(),sourceRepo=el.querySelector('[name=source-repo]').value.trim(),sourceRef=el.querySelector('[name=source-ref]').value.trim()||'HEAD';
      data=await api.skillsSaveSource({id,name,repo:sourceRepo,ref:sourceRef,revision:data.revision});
      const saved=id?data.sources.find(source=>source.id===id):data.sources.at(-1);repo=saved.repo;ref=saved.ref;catalog=null;query='';cardLimit=60;el.close();paint();toast('来源已保存到“我的来源”。');await readStore();
    });
  }
  function syncGroupSelection(el){const inputs=[...el.querySelectorAll('[name=skill]')],count=inputs.filter(input=>input.checked).length;const label=el.querySelector('[data-pick-count]');if(label)label.textContent=`已选 ${count} / ${inputs.length} 个技能`;const all=el.querySelector('[data-pick-all=yes]'),none=el.querySelector('[data-pick-all=no]');if(all)all.disabled=!!el.dataset.pending||count===inputs.length;if(none)none.disabled=!!el.dataset.pending||count===0;}
  function editGroup(id){const group=data.groups.find(g=>g.id===id)||{name:'',skillIds:[]};dialog(id?'编辑分组':'新建分组',`<label class="s-field">分组名称<input name="name" maxlength="40" value="${esc(group.name)}"></label><p class="help-text">一个技能可以属于多个分组。保存分组后，点击“预览并应用”才会改变 Codex 配置。</p><div class="s-pick-toolbar"><span data-pick-count role="status"></span><div class="actions"><button class="btn" type="button" data-pick-all="yes">全选</button><button class="btn" type="button" data-pick-all="no">取消全选</button></div></div><div class="s-pick-list">${data.items.map(i=>`<label><input type="checkbox" name="skill" value="${i.id}" ${group.skillIds.includes(i.id)?'checked':''}><span><strong>${esc(i.name)}</strong><small>${esc(i.description.slice(0,160))}</small></span></label>`).join('')||'<p>先从技能商店安装，或重新读取本机技能。</p>'}</div>`,`<button class="btn" data-close>取消</button>${id&&id!=='common'?'<button class="btn danger" data-submit="delete">删除分组</button>':''}<button class="btn primary" data-submit="save">保存分组</button>`,async(act,el)=>{if(demo)return toast('演示模式不修改本机技能。');data=act==='delete'?await api.skillsRemoveGroup({id,revision:data.revision}):await api.skillsSaveGroup({id,name:el.querySelector('[name=name]').value,skillIds:[...el.querySelectorAll('[name=skill]:checked')].map(n=>n.value),revision:data.revision});el.close();paint();});}
  async function previewGroups(ids){if(demo)return toast('演示模式不修改 Codex 配置。');const plan=await api.skillsPlan({groupIds:ids,revision:data.revision});dialog('切换技能分组',`<p class="s-dialog-intro">配置组合：${esc(plan.groups.join(' + ')||'停用所有分组')}</p><div class="s-change-grid"><section><h3>启用 ${plan.enable.length} 项</h3>${plan.enable.map(n=>`<p>＋ ${esc(n)}</p>`).join('')||'<p>无新增</p>'}</section><section><h3>停用 ${plan.disable.length} 项</h3>${plan.disable.map(n=>`<p>－ ${esc(n)}</p>`).join('')||'<p>无停用</p>'}</section></div><div class="s-notice">保存到 Codex Skills 配置后，请保存正在进行的任务并自行重启 Codex。已有源文件和系统技能不会被删除。</div>`,`<button class="btn" data-close>返回</button><button class="btn primary" data-submit="apply">保存启用配置</button>`,async(_,el)=>{data=await api.skillsApply({token:plan.token});selectedGroups=new Set(data.activeGroupIds);el.close();paint();toast('分组配置已保存，请重启 Codex 后使用。');});}
  async function skillPreview(id){if(demo)return toast('演示模式不下载技能。');const p=await api.skillsPreview({repo,ref,id});const modal=dialog(p.name,`<p class="s-dialog-intro">${esc(p.description)}</p><div class="s-origin">${esc(p.repo)} · ${esc(p.commit.slice(0,12))} · ${p.fileCount} 个文件 · ${p.bytes===null?'按需下载':(p.bytes/1024).toFixed(0)+' KB'}</div><div class="s-preview"><pre>${esc(p.body)}</pre></div><details class="s-license"><summary>查看仓库许可证</summary><pre>${esc(p.license)}</pre></details><h3>安装到分组</h3><div class="s-group-picks">${data.groups.map(g=>`<label><input type="checkbox" name="group" value="${g.id}">${esc(g.name)}</label>`).join('')}</div><p class="help-text">先安装到本机技能库，再到场景分组启用。不会运行安装脚本；已存在的技能不会被覆盖。</p>`,`<button class="btn" data-close>取消</button><button class="btn primary" data-submit="install">安装到技能库</button>`,async(_,el)=>{data=await api.skillsInstall({token:p.token,groupIds:[...el.querySelectorAll('[name=group]:checked')].map(n=>n.value),revision:data.revision});el.close();paint();toast('已安装。到场景分组选择并应用，即可启用。');});translation.attachDetail(modal,p.body);}
  async function click(e){if(translation.handle(e,root))return;const node=e.target.closest('[data-sact]');if(!node||busy)return;const act=node.dataset.sact,id=node.dataset.id;
    if(act==='github-token')return editGithubToken();
    if(act==='more-cards'){cardLimit+=60;root.querySelector('#s-cards').innerHTML=tab==='library'?libraryCards():storeCards();return;}
    if(act==='reload')return load();
    if(act==='tab'){tab=id;query='';cardLimit=60;paint();if(tab==='store'&&!catalog)await readStore();return;}
    if(act==='store'){tab='store';query='';cardLimit=60;paint();if(!catalog)await readStore();return;}
    if(act==='source'||act==='custom-source'||act==='refresh-store'){if(act==='source'){const source=data.sources.find(source=>(source.id||source.repo)===id);if(!source)return;repo=source.repo;ref=source.ref||'HEAD';}if(act==='custom-source'){repo=root.querySelector('#s-repo').value;ref=root.querySelector('#s-ref').value||'HEAD';}catalog=null;query='';cardLimit=60;return readStore(act==='refresh-store');}
    if(act==='add-source'||act==='edit-source'||act==='save-current-source')return editSource(id,act==='save-current-source');
    if(act==='new-group'||act==='edit-group')return editGroup(id);
    if(act==='apply-groups'||act==='switch-group')return action(()=>previewGroups(act==='switch-group'?[...new Set(['common',id])]:[...selectedGroups]));
    if(act==='preview-skill')return action(()=>skillPreview(id));
    if(act==='detail')return action(async()=>{const i=demo?data.items.find(i=>i.id===id):await api.skillsDetail(id);const modal=dialog(i.name,`<p>${esc(i.description)}</p><div class="s-origin">${esc(i.source?.repo||'本机已有技能')}</div><div class="s-preview"><pre>${esc(i.body||'演示内容')}</pre></div>`,`<button class="btn" data-close>关闭</button>`,async()=>{});translation.attachDetail(modal,i.body||'演示内容');});
  }
  return {render};
};
