// Actual app/preload and isolated Skills Hub; GitHub and config writer are offline fixtures.
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const TOML=require('@iarna/toml');
const archive=process.platform==='darwin'?`release/${process.arch==='arm64'?'mac-arm64':'mac'}/Codex Auth Manager.app/Contents/Resources/app.asar/src`:'release/win-unpacked/resources/app.asar/src';
const source=path.resolve(process.argv.includes('--packaged')?archive:'src');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'cam-skills-ui-')),home=path.join(temp,'codex'),userHome=path.join(temp,'user'),bank=path.join(userHome,'.skillshub');
fs.mkdirSync(path.join(home,'skills'),{recursive:true});fs.mkdirSync(path.join(bank,'existing-notes'),{recursive:true});
fs.writeFileSync(path.join(bank,'existing-notes','SKILL.md'),'---\nname: existing-notes\ndescription: Read the local skill introduction while preserving its source files.\n---\n\n# Existing notes\nFirst research paragraph.\nFinal research paragraph.\n');
fs.symlinkSync(path.join(bank,'existing-notes'),path.join(home,'skills','existing-notes'),process.platform==='win32'?'junction':'dir');
fs.writeFileSync(path.join(home,'config.toml'),'model = "fixture"\n');
process.env.CODEX_HOME=home;process.env.CAM_DATA_ROOT=path.join(temp,'vault');app.setPath('userData',path.join(temp,'electron'));
const fixture=require('./fixtures/skills-repository').createRepositoryFixture();
const packet=text=>(Buffer.byteLength(text)+4).toString(16).padStart(4,'0')+text;
const baseFetcher=process.argv.includes('--limited')?async url=>{if(url.startsWith('https://api.github.com/'))return new Response('{}',{status:403,headers:{'x-ratelimit-remaining':'0','x-ratelimit-reset':String(Math.floor(Date.now()/1000)+600)}});if(url.includes('/info/refs'))return new Response(packet(fixture.commit+' HEAD\n')+'0000');if(url.startsWith('https://codeload.github.com/'))return new Response(fs.readFileSync(path.join(__dirname,'fixtures/skills-repository.zip')));return fixture.fetcher(url)}:fixture.fetcher;
// Deliberately slow the first catalog read to exercise loading-state waits.
let authenticatedRequests=0,firstCatalogRequest=true,holdCatalog=false,releaseCatalog;
const fetcher=async(url,options)=>{if(holdCatalog){holdCatalog=false;await new Promise((resolve,reject)=>{releaseCatalog=()=>reject(Error("Delayed catalog failure"))})}if(firstCatalogRequest){firstCatalogRequest=false;await new Promise(resolve=>setTimeout(resolve,500))}if(options?.headers?.Authorization){assert.ok(url.startsWith('https://api.github.com/'));authenticatedRequests++;if(url==='https://api.github.com/repos/sample/skills')return new Response('{"private":false}');return fixture.fetcher(url)}return baseFetcher(url,options)};
let translationRequests=0,translationCalls=0,holdTranslation=false,releaseTranslation,holdBodyTranslation=true,releaseBodyTranslation;const translationInputs=[];
const holdRequest=(signal,setRelease)=>new Promise((resolve,reject)=>{const abort=()=>reject(Error('Controlled translation aborted'));signal.addEventListener('abort',abort,{once:true});setRelease(()=>{signal.removeEventListener('abort',abort);resolve();});});
const translationFetcher=async(url,options)=>{translationRequests++;assert.equal(options.headers.Authorization,undefined);const query=new URL(url).searchParams,text=query.get('q')||query.get('text[]');if(holdBodyTranslation&&text==='Final research paragraph.'){holdBodyTranslation=false;await holdRequest(options.signal,release=>releaseBodyTranslation=release);}if(holdTranslation){holdTranslation=false;await holdRequest(options.signal,release=>releaseTranslation=release);}if(url.includes('suapi.net')||new URL(url).hostname==='api.qvqa.cn')return new Response('{}',{status:503});assert.ok(url.startsWith('https://api.mymemory.translated.net/get?'));return new Response(JSON.stringify({responseStatus:200,responseData:{translatedText:'合成中文译文，仅用于测试'}}))};
const modulePath=path.join(source,'skills/manager'),factory=require(modulePath).createSkillsManager;
require(modulePath).createSkillsManager=options=>{const manager=factory({...options,userHome,bank,fetcher,translationFetcher,writeConfig:async(h,changes)=>{const config=await require(path.join(source,'skills/config')).readConfig(h);config.skills={config:await require(path.join(source,'skills/config')).patchEntries(config.skills?.config||[],changes)};await fsp.writeFile(path.join(h,'config.toml'),TOML.stringify(config));}});const translate=manager.translate;manager.translate=(...args)=>{translationCalls++;translationInputs.push(args[0].text);return translate(...args);};return manager;};
require(path.join(source,'main'));
let win;const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const evaluate=code=>win.webContents.executeJavaScript(code);
const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
async function until(check,label){for(let i=0;i<100;i++){if(await check())return;await sleep(80)}throw Error('Timeout: '+label);}
const input=(selector,value)=>evaluate(`{const el=document.querySelector(${JSON.stringify(selector)});el.value=${JSON.stringify(value)};el.dispatchEvent(new Event('input',{bubbles:true}));}`);
async function capture(name){await evaluate('document.querySelector("#toast").style.display="none"');win.showInactive();await sleep(180);fs.mkdirSync('output/skills',{recursive:true});fs.writeFileSync('output/skills/'+name+'.png',(await win.webContents.capturePage()).toPNG());}
async function assertIntroTranslation(label){
  const intro=await evaluate('document.querySelector("#skills-dialog .s-dialog-intro").textContent'),body=await evaluate('document.querySelector("#skills-dialog .s-preview pre").textContent'),beforeInputs=translationInputs.length,beforeGithub=fixture.requests.length;
  assert.equal(await evaluate('document.querySelector(".s-translation-intro [data-t-intro]").textContent'),'翻译简介',label+' has an explicit intro action');await click('.s-translation-intro [data-t-intro]');
  await until(()=>evaluate('document.querySelector(".s-translation-intro .s-t-attribution")?.textContent.includes("仅供阅读")'),label+' intro translated');
  assert.deepEqual(translationInputs.slice(beforeInputs),[intro],label+' submits only the existing description, never the body');assert.deepEqual(fixture.requests.slice(beforeGithub),[],label+' intro requires no GitHub metadata fetch');
  assert.equal(await evaluate('document.querySelector("#skills-dialog .s-dialog-intro").textContent'),intro,label+' preserves the original introduction');assert.equal(await evaluate('document.querySelector("#skills-dialog .s-preview pre").textContent'),body,label+' preserves the body');assert.equal(await evaluate('document.querySelector(".s-t-detail-result").hidden'),true,label+' leaves body translation independent');
  assert.ok((await evaluate('document.querySelector(".s-translation-intro .s-translated-text").textContent')).includes(/[A-Za-z]{3}/.test(intro)?'合成中文译文':intro));
  assert.equal(await evaluate('document.querySelector(".s-translation-detail .s-t-status").textContent'),'','intro completion must not claim the body has been translated');
  const beforeToggle=translationCalls;await click('.s-translation-intro [data-t-intro-original]');assert.equal(await evaluate('document.querySelector(".s-t-intro-result").hidden'),true);await click('.s-translation-intro [data-t-intro-original]');assert.equal(await evaluate('document.querySelector(".s-t-intro-result").hidden'),false);assert.equal(translationCalls,beforeToggle,'intro visibility controls make no translation request');
}
async function assertDisabledIntro(action,label){
  const before=translationCalls;await click(action);await until(()=>evaluate('!!document.querySelector("#skills-dialog .s-dialog-intro")'),label+' disabled detail');
  assert.equal(await evaluate('!!document.querySelector("#skills-dialog [data-t-intro]")'),false,label+' hides intro translation while disabled');assert.equal(translationCalls,before,label+' opens without sending translation text');await click('#skills-dialog [data-close]');await until(()=>evaluate('!document.querySelector("#skills-dialog")'),label+' disabled detail closed');
}
setTimeout(()=>{console.error('SKILLS FAIL timeout');app.exit(1)},50000);
(async()=>{
  await until(()=>{win=BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().includes('manager.html'));return win&&!win.webContents.isLoading()},'startup');win.setSize(1440,1020);win.webContents.setBackgroundThrottling(false);
  await click('[data-page=skills]');await until(()=>evaluate('document.querySelectorAll(".s-card").length===1'),'existing skill');
  await assertDisabledIntro('[data-sact=detail]','local');
  assert.equal(translationRequests,0,'translation is opt-in');await click('[data-t-action=settings]');assert.deepEqual(await evaluate('[...document.querySelectorAll("[name=translation-provider]:checked")].map(el=>el.value)'),['suapi','qvqa','mymemory'],'fresh defaults include the three disclosed services');await click('[name=translation-enabled]');assert.ok(await evaluate('document.querySelector("#skill-translation-settings").open&&document.querySelector("#skill-translation-settings").getBoundingClientRect().height>100'),'translation settings visible');await sleep(500);await capture('translation-settings');await click('[data-t-save]');await click('[data-t-action=one]');await until(()=>evaluate('document.querySelector(".s-t-result").textContent.includes("合成中文译文")'),'local translation');assert.ok(translationRequests>=2,'failed primary uses fallback');const beforeLocalDetail=translationCalls;await click('[data-sact=detail]');await until(()=>evaluate('!!document.querySelector("[data-t-detail]")'),'local detail');assert.equal(translationCalls,beforeLocalDetail,'opening local detail does not automatically translate');assert.equal(await evaluate('getComputedStyle(document.querySelector("[data-t-intro-original]")).display'),'none','hide-translation control stays hidden until a result exists');await assertIntroTranslation('local detail');await capture('translation-intro');await click('[data-t-detail]');
  await until(()=>!!releaseBodyTranslation,'final body segment held');await until(()=>evaluate('!document.querySelector(".s-t-detail-result").hidden&&document.querySelector(".s-t-detail-result pre").textContent.includes("合成中文译文")'),'partial body visible before completion');
  assert.ok(await evaluate('document.querySelector(".s-t-detail-result pre").textContent.includes("Final research paragraph.")'),'unfinished body segment keeps original');assert.match(await evaluate('document.querySelector(".s-translation-detail .s-t-status").textContent'),/\d+\s*\/\s*\d+\s*段/);assert.match(await evaluate('document.querySelector(".s-translation-detail .s-t-attribution").textContent'),/正在翻译/);
  assert.equal(await evaluate('document.querySelector(".s-translation-detail .s-t-stop").textContent'),'取消翻译');assert.equal(await evaluate('document.querySelector(".s-translation-detail .s-t-stop").hidden'),false);await click('.s-translation-detail .s-t-stop');await until(()=>evaluate('document.querySelector(".s-translation-detail .s-t-status").textContent==="已取消"'),'body cancellation completed');assert.ok(await evaluate('document.querySelector(".s-t-detail-result pre").textContent.includes("合成中文译文")'),'cancellation retains completed paragraphs');releaseBodyTranslation=null;await click('[data-t-detail]');await until(()=>evaluate('document.querySelector(".s-translation-detail .s-t-attribution").textContent.includes("仅供阅读")'),'body translation completed');const beforeCachedBody=translationCalls;await click('[data-t-detail]');assert.equal(translationCalls,beforeCachedBody,'complete body cache avoids a repeated IPC call');
  assert.ok(await evaluate('document.querySelector("#skills-dialog .s-preview").textContent.includes("Existing notes")'),'original preserved');await click('#skills-dialog [data-close]');
  await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'body detail closed');await click('[data-t-action=settings]');await click('[name=translation-provider][value=suapi]');await click('[name=translation-provider][value=qvqa]');await click('[data-t-save]');
  await click('[data-sact=detail]');await until(()=>evaluate('!!document.querySelector("[data-t-detail]")'),'detail after provider change');const beforeProviderChange=translationCalls;await click('[data-t-detail]');await until(()=>translationCalls===beforeProviderChange+1,'provider change invalidates full body cache');await until(()=>evaluate('document.querySelector(".s-translation-detail .s-t-attribution").textContent.includes("仅供阅读")'),'changed-provider body completed');await click('#skills-dialog [data-close]');
  await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'changed-provider detail closed');await click('[data-t-action=settings]');await click('[name=translation-provider][value=suapi]');await click('[name=translation-provider][value=qvqa]');await click('[data-t-save]');
  await click('[data-sact=store]');await until(()=>evaluate('document.querySelector("[data-sact=refresh-store]")?.disabled===false'),'initial catalog settled');await click('.s-custom-source summary');await input('#s-repo','sample/skills');await click('[data-sact=custom-source]');await until(()=>evaluate('document.querySelectorAll(".s-store-grid .s-card").length===2'),'market');
  await click('[data-sact=save-current-source]');await input('[name=source-name]','我的科研技能');await click('[data-submit=save-source]');await until(()=>evaluate('!document.querySelector("#skills-dialog")&&document.querySelectorAll(".s-store-grid .s-card").length===2'),'source saved');
  assert.ok(await evaluate('document.querySelector(".s-sources").textContent.includes("我的科研技能")'));
  await click('[data-sact=edit-source]');await input('[name=source-name]','自定义科研来源');await click('[data-submit=save-source]');await until(()=>evaluate('!document.querySelector("#skills-dialog")&&document.querySelector(".s-store-heading").textContent.includes("自定义科研来源")'),'source edited');
  await click('[data-t-action=settings]');await click('[name=translation-enabled]');await click('[data-t-save]');await assertDisabledIntro('[data-sact=preview-skill]','market preview');await click('[data-t-action=settings]');await click('[name=translation-enabled]');await click('[data-t-save]');
  for(const group of ['daily','research']){
    const beforePreview=translationCalls;await click('[data-sact=preview-skill]');await until(()=>evaluate('!!document.querySelector("#skills-dialog [name=group]")'),'preview');assert.equal(translationCalls,beforePreview,'opening market preview does not automatically translate');await assertIntroTranslation('market '+group+' preview');
    assert.ok(await evaluate('document.querySelector(".s-preview").textContent.includes("---")'));await click(`[name=group][value=${group}]`);await click('[data-submit=install]');await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'install');
  }
  assert.equal(await evaluate('document.querySelectorAll(".s-store-grid [data-sact=preview-skill]").length'),0,'installed skills no longer offer another installation');
  assert.equal(await evaluate('document.querySelectorAll(".s-store-grid [data-sact=detail]").length'),2,'installed store cards open the local skill');
  const beforeInstalledDetail=fixture.requests.length;await click('.s-store-grid [data-sact=detail]');await until(()=>evaluate('!!document.querySelector("#skills-dialog .s-preview")'),'installed local detail');
  assert.match(await evaluate('document.querySelector("#skills-dialog .s-preview").textContent'),/daily-notes/);assert.equal(await evaluate('!!document.querySelector("#skills-dialog [data-submit=install]")'),false);assert.equal(fixture.requests.length,beforeInstalledDetail,'reading an installed skill uses local files');
  // Hold the native asynchronous close event until a newer batch owns an in-flight request.
  await evaluate(`{const dialog=document.querySelector('#skills-dialog');dialog.addEventListener('close',event=>{event.stopImmediatePropagation();window.releaseSkillClose=()=>dialog.dispatchEvent(new Event('close'));},{capture:true,once:true});}`);
  await click('#skills-dialog [data-close]');await until(()=>evaluate('typeof window.releaseSkillClose==="function"'),'installed detail close held');
  const sourceMatching=await evaluate(`(async()=>{
    const root=document.createElement('div'),tick=()=>new Promise(resolve=>setTimeout(resolve,0));
    const local=[{id:'known-local',name:'same-name',description:'known origin',enabled:false,groupIds:[],source:{id:'older-catalog-id',repo:'SAMPLE/SKILLS',folder:'skills/known'}},{id:'unknown-local',name:'same-name',description:'unknown origin',enabled:false,groupIds:[],source:null}];
    const catalog=[{id:'remote-known',name:'same-name',repo:'sample/skills',folder:'skills/known'},{id:'remote-unknown',name:'same-name',repo:'sample/skills',folder:'skills/untracked'},{id:'remote-other',name:'same-name',repo:'another/skills',folder:'skills/known'}];
    const ui=window.createSkillsUI({demo:false,toast:()=>{},api:{skillsList:async()=>({revision:1,activeGroupIds:[],groups:[],items:local,warnings:[],history:[],sources:[]}),skillsCatalog:async()=>({repo:'sample/skills',commit:'fixture',items:catalog})}});
    ui.render(root);await tick();root.querySelector('[data-sact=store]').click();await tick();
    return {localIds:[...root.querySelectorAll('[data-sact=detail]')].map(el=>el.dataset.id),installIds:[...root.querySelectorAll('[data-sact=preview-skill]')].map(el=>el.dataset.id)};
  })()`);
  assert.deepEqual(sourceMatching,{localIds:['known-local'],installIds:['remote-unknown','remote-other']},'match repo and folder provenance across catalog IDs; never infer installation from a shared name');
  holdTranslation=true;await click('[data-t-action=batch]');await until(()=>!!releaseTranslation,'market translation request held');
  const afterDelayedClose=await evaluate(`window.releaseSkillClose();delete window.releaseSkillClose;document.querySelector('.s-t-status').textContent`);
  assert.doesNotMatch(afterDelayedClose,/正在取消|已取消/,'closing an untranslated detail must not cancel the newer market batch');releaseTranslation();releaseTranslation=null;
  await until(()=>evaluate('document.querySelectorAll(".s-translated-text").length===2'),'market translation');await capture('translation-store');const beforeDisable=translationRequests;await click('[data-t-action=settings]');await click('[name=translation-enabled]');await click('[data-t-save]');assert.equal(await evaluate('document.querySelectorAll(".s-translation-target").length'),0);await sleep(100);assert.equal(translationRequests,beforeDisable);await click('[data-t-action=settings]');await click('[name=translation-enabled]');await click('[data-t-save]');assert.equal(translationRequests,beforeDisable,'changing preference does not send text');
  if(process.argv.includes('--limited'))assert.ok(await evaluate('document.querySelector("#skills-body").textContent.includes("官方仓库快照")'));await capture('store');
  await click('[data-sact=github-token]');assert.equal(await evaluate('document.querySelector("[name=github-token]").type'),'password');
  const fakeToken='SYNTHETIC_TOKEN_FOR_OFFLINE_TEST_ONLY';await input('[name=github-token]',fakeToken);await click('[data-submit=save-token]');
  await until(()=>evaluate('!document.querySelector("#skills-dialog")&&document.querySelector("[data-sact=github-token]")?.textContent==="Token 已设置"&&!document.querySelector("[data-sact=refresh-store]").disabled'),'token saved and refreshed');
  assert.ok(authenticatedRequests>=3);assert.ok(!JSON.stringify(await evaluate('window.codexAuth.skillsList()')).includes(fakeToken));
  assert.ok(!fs.readFileSync(path.join(temp,'vault/skills/github-token.enc'),'utf8').includes(fakeToken));
  await click('[data-sact=github-token]');assert.equal(await evaluate('document.querySelector("[name=github-token]").value'),'');await capture('github-token');await click('#skills-dialog [data-close]');await capture('store');

  let state=await evaluate('window.codexAuth.skillsList()');assert.equal(state.items.length,3);assert.equal(state.items.filter(i=>i.enabled).length,1,'new installation starts disabled');
  await click('[data-sact=tab][data-id=groups]');await capture('groups');
  for(const group of ['daily','research']){await click(`[data-sact=switch-group][data-id=${group}]`);await until(()=>evaluate('!!document.querySelector("[data-submit=apply]")'),'apply preview');await click('[data-submit=apply]');await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'group applied');}
  state=await evaluate('window.codexAuth.skillsList()');assert.deepEqual(state.activeGroupIds,['common','research']);assert.ok(state.items.find(i=>i.name==='research-review').enabled);assert.ok(!state.items.find(i=>i.name==='daily-notes').enabled);assert.ok(state.items.find(i=>i.name==='existing-notes').enabled);
  assert.ok(fs.lstatSync(path.join(home,'skills','existing-notes')).isSymbolicLink());assert.match(fs.readFileSync(path.join(bank,'existing-notes','SKILL.md'),'utf8'),/Existing notes/);
  await capture('groups-active');await click('[data-sact=tab][data-id=library]');await capture('library');
  await input('#s-search','research');assert.equal(await evaluate('document.querySelectorAll(".s-card").length'),1);await input('#s-search','');
  await click('[data-sact=tab][data-id=groups]');await click('[data-sact=new-group]');await input('#skills-dialog [name=name]','写作');await click('#skills-dialog [name=skill]');await click('[data-submit=save]');await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'save group');assert.equal(await evaluate('document.querySelectorAll(".s-group").length'),4);
  const writingGroup=(await evaluate('window.codexAuth.skillsList()')).groups.find(g=>g.name==='写作');await click(`[data-sgroup="${writingGroup.id}"]`);
  assert.equal(await evaluate('document.querySelectorAll("[data-sgroup]:checked").length'),3);await click(`[data-sact=edit-group][data-id="${writingGroup.id}"]`);await click('[data-submit=delete]');await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'selected group removed');
  assert.equal(await evaluate('document.querySelectorAll("[data-sgroup]:checked").length'),2);assert.ok(await evaluate('document.querySelector(".s-apply-bar strong").textContent.includes("已选 2")'),'selection count excludes removed group');
  await click('[data-sact=apply-groups]');await until(()=>evaluate('!!document.querySelector("[data-submit=apply]")'),'preview after deleting selected group');await click('#skills-dialog [data-close]');
  await click('[data-sact=edit-group][data-id=common]');
  await click('[data-pick-all=yes]');assert.equal(await evaluate('document.querySelectorAll("[name=skill]:checked").length'),3);assert.ok(await evaluate('document.querySelector("[data-pick-all=yes]").disabled'));
  await click('[name=skill]');assert.ok(await evaluate('!document.querySelector("[data-pick-all=yes]").disabled'));assert.ok(await evaluate('document.querySelector("[data-pick-count]").textContent.includes("2 / 3")'));
  await click('[data-pick-all=no]');assert.equal(await evaluate('document.querySelectorAll("[name=skill]:checked").length'),0);assert.ok(await evaluate('document.querySelector("[data-pick-all=no]").disabled'));
  await click('[data-pick-all=yes]');await capture('group-select-all');await click('#skills-dialog [data-close]');assert.deepEqual((await evaluate('window.codexAuth.skillsList()')).groups.find(g=>g.id==='common').skillIds,[],'cancel does not save selection');
  await click('[data-sact=edit-group][data-id=common]');await click('[data-pick-all=yes]');await click('[data-submit=save]');await until(()=>evaluate('!document.querySelector("#skills-dialog")'),'all saved');assert.equal((await evaluate('window.codexAuth.skillsList()')).groups.find(g=>g.id==='common').skillIds.length,3);
  win.setSize(1000,850);await evaluate('document.body.classList.add("dark")');await capture('groups-dark');assert.ok(await evaluate('document.querySelector("#content").scrollWidth<=document.querySelector("#content").clientWidth'));
  win.reload();await until(()=>!win.webContents.isLoading(),'reload');await click('[data-page=skills]');await until(()=>evaluate('document.querySelectorAll(".s-card").length===3'),'persistence');
  await click('[data-sact=store]');await until(()=>evaluate('document.querySelectorAll("[data-sact=source]").length===4'),'source persistence');
  assert.ok(await evaluate('!!document.querySelector("[data-t-action=batch]")'),'translation preference survives reload');const savedSource=(await evaluate('window.codexAuth.skillsList()')).sources.find(s=>s.custom);await click(`[data-sact=source][data-id="${savedSource.id}"]`);await until(()=>evaluate('document.querySelectorAll(".s-store-grid .s-card").length===2'),'source switch');assert.ok(await evaluate('document.querySelector(".s-store-heading").textContent.includes("自定义科研来源")'));
  await capture('custom-sources-dark');holdCatalog=true;await click('[data-sact=refresh-store]');await until(()=>!!releaseCatalog,'catalog held');await click('[data-sact=edit-source]');assert.ok(await evaluate('!!document.querySelector("[data-submit=remove-source]")'),'source management must remain available during catalog loading');await click('[data-submit=remove-source]');await until(()=>evaluate('!document.querySelector("#skills-dialog")&&document.querySelectorAll("[data-sact=source]").length===3'),'source removed during load');releaseCatalog();await sleep(150);assert.ok(!await evaluate('document.querySelector("[data-page=skills].active").textContent.includes("Delayed catalog failure")'));assert.equal((await evaluate('window.codexAuth.skillsList()')).githubToken.configured,true);await click('[data-sact=github-token]');await click('[data-submit=remove-token]');await until(()=>evaluate('!document.querySelector("#skills-dialog")&&!document.querySelector("[data-sact=refresh-store]").disabled'),'token removed');assert.equal(fs.existsSync(path.join(temp,'vault/skills/github-token.enc')),false);assert.equal((await evaluate('window.codexAuth.skillsList()')).items.length,3,'source removal leaves installed skills');
  console.log('SKILLS PASS: existing junction preservation, local/market intro translation consent and isolation, repository browse, preview/license, installed local detail, install disabled, scenario union/switch, config status, selected-group deletion, group edit, persistence, responsive UI. Synthetic data only.');app.exit(0);
})().catch(e=>{console.error('SKILLS FAIL',e);app.exit(1)});
