async (page) => {
  await page.goto('http://127.0.0.1:4318/manager.html?demo=1');
  await page.evaluate(()=>localStorage.removeItem('demo-pro-five-hour'));
  await page.reload();
  await page.setViewportSize({width:1280,height:1000});
  await page.getByRole('heading',{name:'账号管理',exact:true}).waitFor();
  await page.screenshot({path:'output/playwright/aurora-dashboard.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'添加账号',exact:true}).click();
  await page.getByRole('textbox',{name:'账号名称'}).fill('浏览器测试');
  await page.getByRole('button',{name:'通过浏览器登录'}).click();
  await page.getByRole('button',{name:'取消登录'}).waitFor();
  await page.screenshot({path:'output/playwright/login.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'取消登录'}).click();
  if(await page.locator('dialog[open]').count()) throw Error('Login cancellation did not close dialog');
  await page.getByRole('textbox',{name:'搜索账号'}).fill('research');
  if(await page.locator('.account-card').count()!==1) throw Error('Search did not narrow accounts');
  await page.getByRole('textbox',{name:'搜索账号'}).fill('');
  await page.getByRole('button',{name:'切换并重启',exact:true}).first().click();
  await page.getByRole('dialog').getByRole('button',{name:'切换并重启',exact:true}).click();
  await page.getByRole('heading',{name:'创作空间 Plus'}).waitFor();
  await page.getByRole('button',{name:'应用设置',exact:true}).click();
  const proToggle=page.getByRole('checkbox',{name:'Pro 显示 5 小时额度'});
  if(await proToggle.isChecked())throw Error('Pro should default off');
  await proToggle.check();
  await page.getByRole('button',{name:'账号管理',exact:false}).first().click();
  if(await page.locator('.pro-session-disabled').count())throw Error('Enabled Pro quota still hidden');
  await page.getByRole('button',{name:'应用设置',exact:true}).click();
  await page.getByRole('checkbox',{name:'Pro 显示 5 小时额度'}).uncheck();
  await page.getByRole('checkbox',{name:'隐藏邮箱'}).check();
  if(!await page.locator('body').evaluate(el=>el.classList.contains('privacy')))throw Error('Privacy setting failed');
  await page.getByRole('checkbox',{name:'隐藏邮箱'}).uncheck();
  await page.screenshot({path:'output/playwright/settings.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'用量概览',exact:true}).click();
  await page.getByRole('button',{name:'刷新本机统计'}).click();
  await page.getByRole('heading',{name:'模型用量分布'}).waitFor();
  await page.screenshot({path:'output/playwright/aurora-statistics.png',fullPage:true,animations:'disabled'});
  await page.getByRole('button',{name:'订阅额度',exact:true}).click();
  await page.getByRole('heading',{name:'订阅额度',exact:true}).waitFor();
  await page.getByRole('button',{name:'环境体检',exact:true}).click();
  await page.getByRole('heading',{name:'环境体检',exact:true}).waitFor();
  await page.getByRole('button',{name:'操作记录',exact:true}).click();
  await page.getByRole('heading',{name:'本次会话',exact:true}).waitFor();
  await page.goto('http://127.0.0.1:4318/meter.html?demo=1');
  await page.setViewportSize({width:360,height:560});
  await page.locator('#quota-title').filter({hasText:'每周额度'}).waitFor();
  await page.locator('#session').filter({hasText:'97%'}).waitFor();
  await page.getByRole('button',{name:'置顶悬浮窗'}).click();
  if(await page.locator('#pin-btn').getAttribute('aria-pressed')!=='true')throw Error('Pin failed');
  await page.screenshot({path:'output/playwright/aurora-meter.png',animations:'disabled'});
  const bounds=await page.locator('footer').boundingBox();
  if(bounds.y+bounds.height>552)throw Error('Widget footer clipped');
  await page.setViewportSize({width:1280,height:1000});
  await page.goto('http://127.0.0.1:4318/manager.html?demo=1');
  console.log('UI PASS: login cancellation, search, simulated switch, privacy, usage, activity.');
}
