const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("codexAuth", {
  skillsTranslate:input=>ipcRenderer.invoke('skills:translate',input),
  onSkillsTranslationProgress:callback=>{
    const handler=(_event,payload)=>callback(payload);
    ipcRenderer.on('skills:translation-progress',handler);
    return ()=>ipcRenderer.removeListener('skills:translation-progress',handler);
  },
  skillsCancelTranslation:input=>ipcRenderer.invoke('skills:cancelTranslation',input),
  skillsSaveToken:input=>ipcRenderer.invoke('skills:saveToken',input),
  skillsRemoveToken:()=>ipcRenderer.invoke('skills:removeToken'),
  skillsList:input=>ipcRenderer.invoke('skills:list',input),
  skillsCatalog:input=>ipcRenderer.invoke('skills:catalog',input),
  skillsPreview:input=>ipcRenderer.invoke('skills:preview',input),
  skillsInstall:input=>ipcRenderer.invoke('skills:install',input),
  skillsSaveGroup:input=>ipcRenderer.invoke('skills:saveGroup',input),
  skillsRemoveGroup:input=>ipcRenderer.invoke('skills:removeGroup',input),
  skillsSaveSource:input=>ipcRenderer.invoke('skills:saveSource',input),
  skillsRemoveSource:input=>ipcRenderer.invoke('skills:removeSource',input),
  skillsPlan:input=>ipcRenderer.invoke('skills:plan',input),
  skillsApply:input=>ipcRenderer.invoke('skills:apply',input),
  skillsDetail:input=>ipcRenderer.invoke('skills:detail',input),
  knowledgeModels:()=>ipcRenderer.invoke('knowledge:models'),
  knowledgeList:()=>ipcRenderer.invoke('knowledge:list'),
  knowledgeSave:input=>ipcRenderer.invoke('knowledge:save',input),
  knowledgeRemove:(id,revision)=>ipcRenderer.invoke('knowledge:remove',id,revision),
  knowledgeSessions:()=>ipcRenderer.invoke('knowledge:sessions'),
  knowledgeTranscript:id=>ipcRenderer.invoke('knowledge:transcript',id),
  knowledgePreview:request=>ipcRenderer.invoke('knowledge:preview',request),
  knowledgeStart:request=>ipcRenderer.invoke('knowledge:start',request),
  knowledgeState:()=>ipcRenderer.invoke('knowledge:state'),
  knowledgeCancel:()=>ipcRenderer.invoke('knowledge:cancel'),
  knowledgeResume:()=>ipcRenderer.invoke('knowledge:resume'),
  knowledgeDiscard:()=>ipcRenderer.invoke('knowledge:discard'),
  knowledgeExport:id=>ipcRenderer.invoke('knowledge:export',id),
  startLogin: name => ipcRenderer.invoke('login:start', name),
  cancelLogin: () => ipcRenderer.invoke('login:cancel'),
  getLoginState: () => ipcRenderer.invoke('login:state'),
  openLogin: () => ipcRenderer.invoke('login:open'),
  enableFileStore: () => ipcRenderer.invoke('config:enable-file'),
  setWindowTheme: dark => ipcRenderer.invoke('window:set-theme', dark),
  getVersion: () => ipcRenderer.invoke("app:version"),
  getStatistics: () => ipcRenderer.invoke('statistics:get'),
  refreshOfficial: id => ipcRenderer.invoke('account:refresh-official', id),
  refreshLocalData: () => ipcRenderer.invoke('data:refresh-local'),
  checkForUpdates: () => ipcRenderer.invoke("updates:check"),
  openUpdate: target => ipcRenderer.invoke('updates:open', target),
  exportStatistics: () => ipcRenderer.invoke('statistics:export'),
  getState: () => ipcRenderer.invoke("state:get"),
  importCurrent: (displayName) => ipcRenderer.invoke("account:import-current", displayName),
  exportPortable: (password) => ipcRenderer.invoke("account:export-portable", password),
  importPortable: (password) => ipcRenderer.invoke("account:import-portable", password),
  switchAccount: (accountId, options) => ipcRenderer.invoke("account:switch", accountId, options),
  reorderAccounts: (accountIds) => ipcRenderer.invoke("account:reorder", accountIds),
  reauthAccount: (accountId) => ipcRenderer.invoke("account:reauth", accountId),
  updateAccount: (accountId, patch) => ipcRenderer.invoke("account:update", accountId, patch),
  deleteAccount: (accountId) => ipcRenderer.invoke("account:delete", accountId),
  updateSettings: (patch) => ipcRenderer.invoke("settings:update", patch),
  restartCodex: () => ipcRenderer.invoke("codex:restart"),
  getQuota: () => ipcRenderer.invoke("quota:get"),
  getDashboard: () => ipcRenderer.invoke("dashboard:get"),
  getAllAccountsQuota: () => ipcRenderer.invoke("dashboard:all-accounts"),
  getAllUsage: () => ipcRenderer.invoke("dashboard:all-usage"),
  openPath: (targetPath) => ipcRenderer.invoke("path:open", targetPath),
  showMainWindow: () => ipcRenderer.invoke("window:show-main"),
  showWidget: () => ipcRenderer.invoke("window:show-widget"),
  hideWidget: () => ipcRenderer.invoke("window:hide-widget"),
  toggleWidget: () => ipcRenderer.invoke("window:toggle-widget"),
  resizeWidget: (accountCount) => ipcRenderer.invoke("window:resize-widget", accountCount),
  getWidgetTopmost: () => ipcRenderer.invoke("window:get-widget-topmost"),
  setWidgetTopmost: (pinned) => ipcRenderer.invoke("window:set-widget-topmost", pinned),
  startWidgetResize: (edge) => ipcRenderer.invoke("window:resize-widget-start", edge),
  updateWidgetResize: () => ipcRenderer.invoke("window:resize-widget-update"),
  endWidgetResize: () => ipcRenderer.invoke("window:resize-widget-end"),
  collapseWidgetDock: () => ipcRenderer.invoke("window:collapse-widget-dock"),
  widgetPointerEnter: () => ipcRenderer.invoke("window:widget-pointer-enter"),
  widgetPointerLeave: () => ipcRenderer.invoke("window:widget-pointer-leave"),
  onWidgetDockHint: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on("widget:dock-hint", handler);
    return () => ipcRenderer.removeListener("widget:dock-hint", handler);
  },
  onStateChanged: (callback) => {
    const handler = (_event, payload) => callback(payload);
    ipcRenderer.on("state:changed", handler);
    return () => ipcRenderer.removeListener("state:changed", handler);
  },
});
